### ISSUE TITLE
Applying classifications + glossary terms to columns via excel

### ISSUE THREAD

**Issue by zsponaugle** [wjohnson/pyapacheatlas#101]
Hi again. Is it possible to add a classification and/or glossary term to columns using the excel_bulk_entities_upload method? I see the sample has a classifications column. I have tried populating this with an existing classification and it runs without error but nothing shows up in the interface for the column. Other fields like description/data_type update fine. Thanks.

**Comment by zsponaugle** [comment]
Below are the rows as they appear in the spread and the actual data sent. Do I need to include a row for the classification (like I do for the table)? If so what fields are required?


typeName | name | qualifiedName | classifications | [Relationship] table | data_type | description
-- | -- | -- | -- | -- | -- | --
mssql_table | my_table| XXXXXXXXXXX |   |   |   |  
mssql_column | Active | XXXXXXXXXXX  | my_classification | XXXXXXXXXXX  | char | testing


`{
  "entities": [
    {
      "typeName": "mssql_table",
      "guid": -1001,
      "attributes": {
        "name": "my_table",
        "qualifiedName": "XXXXXXXXXXXXX"
      },
      "relationshipAttributes": {}
    },
    {
      "typeName": "mssql_column",
      "guid": -1002,
      "attributes": {
        "data_type": "char",
        "description": "testing",
        "name": "my_field",
        "qualifiedName": "XXXXXXXXXXXX"
      },
      "relationshipAttributes": {
        "table": {
          "typeName": "mssql_table",
          "guid": -1001,
          "qualifiedName": "XXXXXXXXXXXX"
        }
      },
      "classifications": [
        {
          "typeName": "my_classification",
          "attributes": {},
          "propagate": false
        }
      ]
    }
  ]
}`

**Comment by zsponaugle** [comment]
For now I am using the _classify_entity_adds and upload_relationship methods to upload classifications and glossary terms respectively. It works fine but requires two extra calls. Basically I am wondering if there is a way to upload attributes (descriptions), glossary, and classifications to a column all at once? Thank you.

**Comment by wjohnson** [comment]
Sorry, I didn't see this @zsponaugle !  I've labeled it as a bug. You should definitely be able to get classifications uploaded.  Glossary terms are on my todo as part of #74.

**Comment by wjohnson** [comment]
@zsponaugle Can you try doing a classification again from the excel spreadsheet with the latest version on github (not on PyPi)?

Using the below example, I'm able to create a single or multiple classifications on a given column.  I just want to confirm that your scenario works with the latest changes.

typeName | name | qualifiedName | classifications | [Relationship] table | type
-- | -- | -- | -- | -- | --
hive_table | hivetable01 | pyapacheatlas://localtest |   |   |  
hive_column | columnA | pyapacheatlas://localtest#A | MICROSOFT.GOVERNMENT.CHILE.CDI_NUMBER | pyapacheatlas://localtest | string

**Comment by zsponaugle** [comment]
For installing the latest version, is this the correct command --
pip install git+https://github.com/wjohnson/pyapacheatlas

**Comment by wjohnson** [comment]
Fixed with the most current version :-)
