### ISSUE TITLE
Deleting a custom made attribute

### ISSUE THREAD

**Issue by zsponaugle** [wjohnson/pyapacheatlas#110]
Hello. I created a custom attribute under custom templates. It creates a typedef called TERM_TEMPLATE_ENUM_1cfdc185_8187_4e14_96fd_12f11466fa06. I am able to interact with this typedef via the API (get_typedef and upload_typedef) and add/modify/remove choices without issue. However I am unable to delete the typedef all-together. I have tried both delete_typedef and delete_entity.

delete_typedef returns this error ---

```
HTTPError                                 Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyapacheatlas\core\client.py in delete_type(self, name)
    102         try:
--> 103             deleteType.raise_for_status()
    104         except requests.RequestException:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 

HTTPError: 404 Client Error: Not Found for url: https://XXXXXXX.catalog.purview.azure.com/api/atlas/v2/types/typedef/name/TERM_TEMPLATE_ENUM_1cfdc185_8187_4e14_96fd_12f11466fa06

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-3-1f59369c90b3> in <module>
     24 #1cfdc185-8187-4e14-96fd-12f11466fa06
     25 #
---> 26 res = client.delete_type(name='TERM_TEMPLATE_ENUM_1cfdc185_8187_4e14_96fd_12f11466fa06')
     27 
     28 print('FINISHED')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyapacheatlas\core\client.py in delete_type(self, name)
    103             deleteType.raise_for_status()
    104         except requests.RequestException:
--> 105             raise Exception(deleteType.text)
    106 
    107         results = {"message": f"successfully delete {name}"}

Exception: {"requestId":"9fe66e54-8f7a-4cbd-aaf8-571ec2f1a609","errorCode":"ATLAS-404-00-001","errorMessage":"Given typename TERM_TEMPLATE_ENUM_1cfdc185_8187_4e14_96fd_12f11466fa06 was invalid"}
```

I have also tried deleting it via delete_entity by using the GUID. This returns without any error but it doesn't delete anything. Thank you.

**Comment by wjohnson** [comment]
@zsponaugle Can you share the get_typedef results?

Would you also be able to share how you created this typedef in more detail?  Is this through the glossary term template UI?

Have you assigned any entities to this term?  If so, you'll have to delete all of the relationships between the entities and the term. THEN you should be able to delete the term and then you can delete the term type (presumably).

**Comment by wjohnson** [comment]
Closing for now since it looks like you might have addressed this on your own.  Happy to re-open if you still need help!
