### ISSUE TITLE
How to create arbitrary relationship (not lineage and not table-column)

### ISSUE THREAD

**Issue by fBedecarrats** [wjohnson/pyapacheatlas#111]
Hello,
Among the package feature, the README indicates that it is possible to create arbitrary relationships between entities and upload relationship definitions. Unfortunately, I failed to find indications on how to proceed in the documentation and in the Excel template. For instance, I would like to create a "hosting" relationship between an entity of type "server" and an entity of type "database". The workaround I found is using the UpdateLineage sheet from the template, parse it with reader.parse_update_lineage() and then load it with client.upload_entities(). But it is not satisfactory, as the relationships between host servers and hosted databases are typed as data lineages and appear on the lineage graphs, which is not appropriate.
Could you please provide some guidance on how to achieve such type of relationship definitions?
Many thanks and best regards,
FB

**Comment by wjohnson** [comment]
I'm sorry you didn't find it in the docs!  First question, what was the first place you looked so I can improve the docs?  I have it listed on the Wiki under the [BulkEntities tab](https://github.com/wjohnson/pyapacheatlas/wiki/Excel-Template-and-Configuration#bulkentities-tab).  The designation of table and column is the most generic way of thinking of it but the same principle applies to server and database as well.

Second question: Did you already create the type with the relationship attribute defined?  Unfortunately, I don't currently expose a template for creating relationship attributes in Excel currently but there are [API samples](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/create_relationships.py) in the repo as well.

So, assuming you've created the relationship attribute, you'd use the bulk entity tab to do this.  Your sheet would look something like this.  You must specify the parent object in the sheet and that parent object must appear BEFORE your child objects reference them in the `[Relationship] server` column.

typeName | name | qualifiedName | classifications | [Relationship] server
-- | -- | -- | -- | --
server | myServer | custom://myserver |   |  
database | myDb1 | custom://myserver/myDb1 |   | custom://myserver
database | myDb2 | custom://myserver/myDb2 |   | custom://myserver



There's actually an [Excel sample of this behavior](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/excel/excel_bulk_entities_upload.py) as well and while it does show a table column relationship, assuming your type has been defined with "server" and "database", you'd just change the column name in excel to reflect your relationship attribute name from child to parent.

**Comment by fBedecarrats** [comment]
Thanks @wjohnson for this quick and complete answer.

**On your first question** : I first went to [the main README](https://github.com/wjohnson/pyapacheatlas/blob/master/README.md), then to the subsequent pages that it was referring to for this matter: the [Excel samples README](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/excel/README.md), and [the Excel Template and Configuration](https://github.com/wjohnson/pyapacheatlas/wiki/Excel-Template-and-Configuration). The first one was suggesting that the Bulk Entities sample was applying to "simple relationship mapping (e.g. the columns of a table)", which suggested it was possible to do other kind of simple relationships, but I couldn't figure out how. The second one was only referring to table-column relationships. I think that adding an explicit mention to other types of relationships in [the BulkEntities section](https://github.com/wjohnson/pyapacheatlas/wiki/Excel-Template-and-Configuration#bulkentities-tab) would help others with similar needs (and limitations) like me.

**On your second question** : I will make tests with your indications and revert back to you by next week on this.

Many thanks again

**Comment by wjohnson** [comment]
Ah! This is great feedback.  Thank you for sharing your path and ideas.

Looking forward to hearing how it goes!

**Comment by wjohnson** [comment]
I'm going to close it since it's been a couple months but let me know if you still need any help!

**Comment by fBedecarrats** [comment]
Yes, thank you Will. I made an attempt that failed in April, but I'm pretty sure that it is because I didn't read the documentation closely enough. I had to switch to another project and I should come back to Atlas in August or September. I'll send an update then. Thanks again and best regards.

**Comment by wjohnson** [comment]
Sounds like a plan! Keep me in the loop!
