### ISSUE TITLE
How can I add contacts (owners and experts) to an asset? 

### ISSUE THREAD

**Issue by IagoFranco** [wjohnson/pyapacheatlas#115]
Hi @wjohnson 
We are trying to add some contacts to an asset, that we already know the expert and owner IDs.

Is there any way to do this? Our expectations is to add contacts as we can add classifications using "client.classify_entity".

I don't know, is there something like "client.add_contacts" and passing the list with experts and owners in parameters?

I'm doing like this:

```
input01 = AtlasEntity(
                name="MTCCARLT",
                typeName= "azure_sql_table",
                qualified_name= <qualifiedname>,
                guid= <guid>,
                contacts=asset["contacts"]
            )
```
This "asset["contacts"]" have this structure:
{'Expert': [{'id': 'assetid'}], 'Owner': [{'id': 'assetid'}]}

But it doesn't edit properly when I run **client.upload_entities(input01)**
This asset already exists on Purview, what I'm trying to do is add Owner and Experts on it.

Thank you very much!

**Comment by wjohnson** [comment]
@IagoFranco I think my internal notes are a bit confusing on this, sorry about that.  Take a look at the docstring and not the inline comment.

```
:param dict(str, dict(str, list(dict(strt,str)))), optional contacts:
        Contacts should contain keys Experts and/or Owners. Their values should
        be a list of dicts with keys id and info. Id is a microsoft graph
        object id. Info is a string of extra information.
```

If your `assetid` isn't a valid AAD object Id representing a user, it will fail to appear in the UI.

Please let me know if assetid is an object id and you're still not getting what you're looking for.

This is related to the work I want to get done on #86 but I haven't had the time to figure out the Microsoft Graph API calls :-(

**Comment by IagoFranco** [comment]
Hi @wjohnson 
Thank you so much for your support.

I'm actually copying from another asset that has contacts configured, so the ID for the user is valid.
I still can't make it work, please see if you can help me:

This is my code:
```
input01 = AtlasEntity(
                name= entityHom["attributes"]["name"],
                typeName= entityHom["typeName"],
                qualified_name= entityHom["attributes"]["qualifiedName"],
                guid= entityHom["guid"],
                contacts= prdAsset["contacts"]
            )
            
            result = client.upload_entities(input01)
```
The structure for "prdAsset["contacts"]" is:
{'Expert': [{'id': 'a4f441db-bb61-44f4-9ba8-d67eb127a112',
   'info': 'Data Steward'}],
 'Owner': [{'id': '5772e578-6c4a-4d51-8283-7c9b60e4a5e2',
   'info': 'Data Steward'}]}

Am I doing something wrong? Could you give me an exemple of what I need to do?

Thank you!!

**Comment by wjohnson** [comment]
Here's a working basic example.  Your syntax looks right!  I'd ask for you to double check on those guids and be sure they're real object ids in AAD.  Maybe try creating an asset like the one below with those ids and if that fails, I'd suggest a support ticket unfortunately :(

```
_ae = AtlasEntity(
    "entitywithcontacts",
    "DataSet",
    "entitywithcontacts",
    guid=-1,
    contacts={
        "Expert":[{"id":"f123-xxx-yyy-zzz-123", "info": "This is Will"}],
        "Owner":[{"id":"f123-xxx-yyy-zzz-123", "info": "This is Will as an owner"}]
    }
)

results = client.upload_entities(_ae)

print(json.dumps(results, indent=2))
```

**Comment by IagoFranco** [comment]
Hi @wjohnson 

I'm doing like this:
```
input01 = AtlasEntity(
                name= entityHom["attributes"]["name"],
                typeName= entityHom["typeName"],
                qualified_name= entityHom["attributes"]["qualifiedName"],
                guid= entityHom["guid"],
                contacts={
                    "Expert":[{"id":"a4a841db-bb662-44n5-9aa8-d67eb127a112", "info": "This is Will"}],
                    "Owner":[{"id":"5772e488-6c6a-4d18-8253-7c9b60e4a5e2", "info": "This is Will as an owner"}]
                }
            )
            
            result = client.upload_entities(input01)
```
I've change with your suggestion, I just include the ID, the info is the same.

But I'm getting: {'mutatedEntities': {}, 'guidAssignments': {}}
It seems that this information is beeing ignored.
This supports for assets already created, because what I'm trying to do is updating an asset that is already scaned.
When I try to update "description" field, it works with this model, but not the contact information.

Do you have any thought on why this is happening?

**Comment by wjohnson** [comment]
Oof! What version of PyApacheAtlas are you running on?

The contacts attribute is only available on [0.5.0](https://github.com/wjohnson/pyapacheatlas/releases/tag/0.5.0) and would silently ignore the contacts attribute in earlier versions.

**Comment by IagoFranco** [comment]
@wjohnson 
OMG, I can't believe it was exacly that!
I was running on 0.4.1 version :S

Now it's working, sorry about that hahah

Thank you very much!

**Comment by wjohnson** [comment]
Huzzah!  I'm glad it's working now!!!

Thank you for continuing to use the library!!
