### ISSUE TITLE
Add labels support 

### ISSUE THREAD

**Issue by kumarmisra** [wjohnson/pyapacheatlas#131]
Hi,

Can you please add labels support in AtlasEntity ? Currently anything you add in excel adds as an attribute , whereas labels are part of root level like typeName.

**Comment by wjohnson** [comment]
Sure thing!

Just to be sure, you're looking for support of the labels key in the root of the atlas entity and it should take an array of strings, right?

As per the [Atlas docs](
https://atlas.apache.org/api/v2/json_AtlasEntity.html) it looks like you'd want to be able to add multiple strings to it in a single excel cell.

**Comment by kumarmisra** [comment]
Yes. You are exactly correct.

**Comment by wjohnson** [comment]
@kumarmisra please see [this branch](https://github.com/wjohnson/pyapacheatlas/tree/feature/readerSupportsRoot) that has support for adding labels in the bulk entity upload.

The template columns would look like:
|typeName|name|qualifiedName|[root] labels|
|----|----|-----|----|
DataSet|myname|my_qualified_name|abc;banana;test

The delimiter is `;` (semi-colon) by default.

In this branch, the `classifications` column is no longer required. If you are using classifications, you can still add the classifications by changing the column header to `[root] classifications`

**Comment by kumarmisra** [comment]
Thanks for the quick turnaround, I will look into it soon.

**Comment by kumarmisra** [comment]
Hi,

I think labels are created while new entity is created , but looks like update is not working.

**Comment by wjohnson** [comment]
@kumarmisra  - That's a limitation of Atlas itself.  If you want to update an existing label, you need to call a different endpoint than the /entity/bulk.  This applies to things like classifications, custom attributes, and business metadata too. Each one has their own endpoint to hit for updates.

I can add that functionality BUT it could result in a lot of API calls and it may overwrite values if you don't specify the whole label or custom attribute or business metadata.

In your use case, would you expect a user to pull down existing labels and include them in the spreadsheet?

Do you care if your upload destroys existing labels?

**Comment by kumarmisra** [comment]
@wjohnson thanks for quick reply !! I am good with what we have.

**Comment by wjohnson** [comment]
Thanks @kumarmisra ! I appreciate you using the package and it will be available on pypi by this weekend for everyone else.  Thank you for your feedback!!

**Comment by kumarmisra** [comment]
Thank you @wjohnson , it is really nice and user friendly !!
