### ISSUE TITLE
What would it be the efficient way to get all Azure SQL Columns from Purview?

### ISSUE THREAD

**Issue by IagoFranco** [wjohnson/pyapacheatlas#147]
Hi @wjohnson how are you?

We need to extract all assets from, but when we try to get all columns, starts to be a problem, because the search option doesn't currently bring this type of asset (columns).

We know that there's a way to search by the qualifiedName, using UniqueAttribute API, see:
![image](https://user-images.githubusercontent.com/68740646/129098068-41776900-bc84-47e6-8e3e-052335f79a20.png)

Do you think that this should be implemented in the PyApacheAtlas framework?
There's an easy way to extract every asset from Purview, like a dump or something?

Thank you very much!

**Comment by wjohnson** [comment]
Hi, @IagoFranco !  What's the entry point?  Do you want to...

* search for a term and then grab all columns of the SQL Tables's that match the term or...
* You know the database and schema and you want to grab all of the columns for all of the tables?

Here's an example starting at the schema. You could start at the database level or server level, it's just repeating these steps (query the qualified name of the root, extract the right relationship attribute, query those guids, grab the relevant relationship attribute from the response, query those guids, etc.)

The only other caveat is that if you have thousands of tables or columns, Purview will take a while to respond. You might consider breaking up the get_entity calls so you don't grab thousands of guids at a time.

Does this help?

```python
# Assuming you want to get all of the columns from all tables in a given schema
schema = client.get_entity(
    qualifiedName="mssql://YOURSERVER.database.windows.net/YOURDATABASE/YOURSCHEMA",
    typeName="azure_sql_schema"
)

# Confirm this actually returned a result
if schema["entities"]:
    if "relationshipAttributes" not in schema["entities"][0]:
        print("Response from Atlas failed to retrieve relationship attributes")
        exit(1)
    # Grab the first result
    rel_schema = schema["entities"][0]
    # an azure_sql_schema has a tables relationship attribute that stores all of its tables
    if "tables" not in rel_schema["relationshipAttributes"]:
        print("Response from Atlas does not include tables relationship")
    
    tables = rel_schema["relationshipAttributes"]["tables"]
    # Iterate over all of the tables and grab their guids
    table_guids = [t["guid"] for t in tables if "guid" in t]
    # Query those tables so that we can get the referred entities that are columns
    tables_response = client.get_entity(table_guids)

    # For every referred entity, check if they are an azure_sql_column
    for refEntity in tables_response["referredEntities"].values():
        if refEntity["typeName"] == "azure_sql_column":
            # If they are an azure_sql_column: Do Somethign!
            print(refEntity["attributes"]["qualifiedName"])
    
else:
    print("There is no schema that matches your query results")

```

**Comment by IagoFranco** [comment]
Hi @wjohnson 
The entry point is exacly that, I want to get all of the columns from all tables in a given schema (considering also ALL schemas).
The sample that you provided fits perfectly.

But, when I'm trying to reproduce I'm getting an error, please see:
![image](https://user-images.githubusercontent.com/68740646/129195061-917f1b9b-232b-4984-87e7-fb3e0ad5d72d.png)

In my case, I have more than 4000 tables, and I am passing everythin in the client.get_entity(table_guids).
I made a test passint just 100 tables and it worked!
I think that Purview is not prepared to respond this amount of request at the same time.

Do you have any suggestion on this case?

**Comment by wjohnson** [comment]
Ah!  Shoot!  Yes, this is a known issue where pulling down thousands of entities can cause a slowdown and ultimately a timeout :(

I would suggest you do some iterating through the table_guids like this snippet. You need to find the right increment (I'm assuming 500 entities will be okay for Purview to handle but maybe it's less if you have a lot of columns in those tables)
```python
table_guids = [t["guid"] for t in tables if "guid" in t]
increment = 500
for start_pos in range(0,len(table_guids), increment):
    tables_response = client.get_entity(table_guids[start_pos:(start_pos+increment)])
    for refEntity in tables_response["referredEntities"].values():
        if refEntity["typeName"] == "azure_sql_column":
            print(refEntity["attributes"]["qualifiedName"])
```

**Comment by IagoFranco** [comment]
Hi @wjohnson 
Thank you so much!
I had to increment by 100, but it worked very nice actually.
The code is cleaner and it runs in minutes, that's very fast comparing to my previous version of it.

Thank you!

**Comment by wjohnson** [comment]
@IagoFranco glad that it worked out!  Thanks for sharing your increment count! Crazy that you could only pull down that many at a time :(

Let me know if you run into any other issues!
