### ISSUE TITLE
How to input data in excel for customAttributes ?

### ISSUE THREAD

**Issue by kumarmisra** [wjohnson/pyapacheatlas#153]
Hi,

Can you please help me on how to put data in excel so that it can parse it for customAttributes as dict?

**Comment by wjohnson** [comment]
@kumarmisra if you're willing to try out the release branch checkout 6d409615401c7fe1a41733c16eebcab17b068c6c and then the bulk entities tab supports a column header of `[custom] attributeName` and then it will add `attributeName as a key to the customAttributes object.

**Comment by kumarmisra** [comment]
@wjohnson Initial test looks good, will test some more and update you !!

**Comment by wjohnson** [comment]
Closed with #170
