### ISSUE TITLE
Is there any way to get all assets based on updateTime?

### ISSUE THREAD

**Issue by IagoFranco** [wjohnson/pyapacheatlas#156]
Hi @wjohnson hope you are well and safe.

I want to understand if there's any way to get assets based on updateTime, to see only those assets that were updated related to the last week for example.

Thank you very much!

**Comment by wjohnson** [comment]
@IagoFranco are you looking at Azure Purview or Apache Atlas?

I think with Apache Atlas, you can access those attributes with the DSL search: https://atlas.apache.org/2.0.0/Search-Advanced.html  See the "Using Date Literals" section. They use createTime on a table type so I'm not sure if that's a root property or if that's an attribute on the table type.

**Comment by IagoFranco** [comment]
Hey @wjohnson 
I'm sorry, I'm looking at Azure Purview..
Sorry not mentioned :(

**Comment by wjohnson** [comment]
@IagoFranco - I did some testing inside of Purview and I could NOT figure out how to accomplish this.

I think this is possible with Atlas but the Purview doesn't have all the same search features as Atlas :(

**Comment by IagoFranco** [comment]
@wjohnson Thank you very much! 
If we find a way to do it somehow, we can bring here to contribute as a sample for sure :)
Thank you!
