### ISSUE TITLE
ExcelReader Support an AtlasObjectId in the [Relationship] field

### ISSUE THREAD

**Issue by wjohnson** [wjohnson/pyapacheatlas#159]
Currently a user cannot provide a simple guid or entity's type and qualified name in the BulkEntities tab. Instead, they have to provide a string that is a qualified name that has already been seen. In addition, this only supports a single qualified name being provided.

This makes it difficult to:
* Update an entity without updating its related entity.
* Provide multiple relationships for a given row (e.g. create a table and point to the existing columns)

I'm proposing allowing for a special value that will resolve to an AtlasObjectId entity.

```
AtlasObjectId(guid:abc-def-123)
AtlasObjectId(typeName:DataSet qualifiedName:myQualifiedName)
```

This would enable you to NOT specify the entity in the spreadsheet and make it easier to specify multiple relationships too (for existing entities)

**Comment by mwbrent** [comment]
when attempting to create a relationship using the above method, getting error:

`Invalid instance creation/updation parameters passed : mssql_table.sinks={guid=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}: invalid value for type array<objectid>`

Trying to create a relationship between two mssql_table entities and passing in the form of AtlasObjectId(guid:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) under a column header of [Relationship] sinks

**Comment by wjohnson** [comment]
@mwbrent please feel free to open a separate issue on this but that error is saying that the relationship `sinks` requires an array.

If you're using the Excel features you have to so something like `AtlasObjectId(guid:xxxx);` with a trailing colon to indicate it's an array.  It's a bit of a hack and would be very much open to suggestions to make it better.

**Comment by mwbrent** [comment]
> @mwbrent please feel free to open a separate issue on this but that error is saying that the relationship `sinks` requires an array.
> 
> If you're using the Excel features you have to so something like `AtlasObjectId(guid:xxxx);` with a trailing colon to indicate it's an array. It's a bit of a hack and would be very much open to suggestions to make it better.

Thanks @wjohnson.   Was missing the ;  

works perfectly now.
