### ISSUE TITLE
Error: mandatory attribute value missing in type azure_cosmosdb_container

### ISSUE THREAD

**Issue by Vigneshg98** [wjohnson/pyapacheatlas#161]
Hi @wjohnson 

It was very helpful for us to Create Column Mapping Lineage using Pyapacheatlas packages. Thanks to you!
We are stuck up with an issue that is described below. It would be a great help if you could help us resolve the same.

While trying to create Column Mapping Lineage between Azure Cosmos DB SQL API Collection and Azure Blob Resource Set in Azure Purview, it is throwing the below error.

Note: It is working fine with 2 Azure Blob Resource Set

**Sample Code Snippet:**
```
column_mapping = '''
[
  {
    "ColumnMapping": [
      { "Source": "LastName", "Sink": "lastname" },
      { "Source": "Id", "Sink": "id" }
    ],
    "DatasetMapping": {
      "Source": "https://****/dbs/***/colls/***",
      "Sink": "https://****/***/{SparkPartitions}"
    }
  }
]
'''
def createLineageProcess(self, process_name, process_input, process_output, column_mapping):
    process = AtlasProcess(
      name=f"{process_name}",
      typeName="ProcessWithColumnMapping",
      qualified_name="https://***/lineage/colMapLineage",
      inputs=[process_input],
      outputs=[process_output],
      guid=self.gt.get_guid(),
      attributes={"columnMapping": json.dumps(column_mapping)}
    )
    results = self.client.upload_entities(
        [process, process_input, process_output]
    )
    print(json.dumps(results, indent=2))

```

**Error:**
```
"errorMessage":"Invalid instance creation/updation parameters 
passed : azure_cosmosdb_sqlapi_collection.resourceLink: 
mandatory attribute value missing in type azure_cosmosdb_container"
```

**Comment by wjohnson** [comment]
Thank you for using PyApacheAtlas!

It looks like you are using a type with a required attribute.  You need to
provide azure_cosmosdb_sqlapi_collection.resourceLink when referencing that
entity and doing a bulk upload.
If the input / output entity already exists, you can specify just the guid
with {“guid”: “123-abc-456”} as the object passed to the input or output of
the process entity (within a list like usual).

Another way of doing this is to create the AtlasEntity like you did for
process input and output BUT if the entity exists already, you can specify
a None for the guid and DO NOT include this entity in the bulk upload. By
not including a guid, the Atlas Process will convert the entity in the
input or output to an AtlasObjectId which consists of just the qualified
name and type (as specified in the Atlas Entity you created).

That last option is probably easiest if the entity already exists.

If the entity does NOT exist and you are creating it for the first time,
you MUST include this attribute when creating the entity and uploading it.

I hope that helps!  Please try one of the options above or let me know if I
misunderstood your question.

Lastly, to find all the required attributes, you’ll need to pull the type
definitions and read through them. There’s no way around diving into the
type defs and tracing through the super types to find all required
attributes.

**Comment by Vigneshg98** [comment]
@wjohnson  Thanks for a quick reply.

The below is the AtlasEntity Object used to create process_input
```
gt = GuidTracker()
AtlasEntity(
      entity,
      'azure_cosmosdb_sqlapi_collection',
      'https://***/dbs/***/colls/***',
      guid = gt.get_guid()
    )
```
I tried passing  _azure_cosmosdb_sqlapi_collection.resourceLink_ instead of  _azure_cosmosdb_sqlapi_collection_. 
Also passing **None** as guid.

I couldn't figure out what is to be changed exactly.

**Comment by wjohnson** [comment]
@Vigneshg98 Please try something like the below:

* process_input should STILL be azure_cosmosdb_sqlapi_collection
* The guid you provide should be None
* The client.upload_entities should **only reference the new entities** you are creating / updating.
* In this case, the entity that is represented by process_input exists already so when you provide a None for guid, PyApacheAtlas will automatically convert this to the "AtlasObjecId" that contains only type name and the qualified name in the right format for upload.

Would you please try setting guid to None and then removing process_input from the upload_entities list and let me know if you succeed?


```
gt = GuidTracker()

process_input = AtlasEntity(
      'myEntityName',
      'azure_cosmosdb_sqlapi_collection',
      'https://***/dbs/***/colls/***',
      guid = None
    )

process = AtlasProcess(
      name="myProcessName",
      typeName="ProcessWithColumnMapping",
      qualified_name="https://***/lineage/colMapLineage",
      inputs=[process_input],
      outputs=[process_output],
      guid=gt.get_guid(),
      attributes={"columnMapping": json.dumps(column_mapping)}
    )
    results = client.upload_entities(
        [process, process_output]
    )
```

**Comment by Vigneshg98** [comment]
@wjohnson That worked!

Thanks a lot for your immediate responses and help. Will get back to you if we face any issues on our path.
