### ISSUE TITLE
Adding a custom attribute to an entity

### ISSUE THREAD

**Issue by ravigit94** [wjohnson/pyapacheatlas#163]
I would like to add a custom attribute to an entity (a csv file stored on ADLS). I tried using the following functions, but can't see the property on the Azure Purview UI:

ae = AtlasEntity(name="employees.csv", typeName= "azure_datalake_gen2_path", qualified_name="https://dvtransaction.dfs.core.windows.net/employee/HR/employees.csv", guid="ada62b29-9ec9-49a3-b01f-513add3c9003")
ae.addCustomAttribute(apple="banana")
ae.addBusinessAttribute(biz1={"prop1":"abc"})

Also is there a way to add a property in "Properties - advanced" section for a given entity (that is not custom).

I would like to highlight that I don't want to create custom entity, rather looking to add additional properties to a scanned entity from ADLS such as csv, txt and parquet files. The typename of the entity is: "azure_datalake_gen2_path"

Can you please help.

Thank You

**Comment by wjohnson** [comment]
Hi, @ravigit94 - Business and Custom Attributes are only supported for Apache Atlas version 2.1 and above.  Unfortunately, Purview apparently is on Atlas 2.0.

I believe the Properties - Advanced section is reserved for custom relationships. You would need to create a relationship definition `pyapacheatlas.core.typedefs.RelationshipTypeDef` and then upload that typedef. See this [Purview REST API video](https://www.youtube.com/watch?v=4qzjnMf1GN4&t=2098s) for more information on relationship types.

**Comment by ravigit94** [comment]
Thanks, that worked.
