### ISSUE TITLE
Column Level Process Mapping not creating expected Lineage

### ISSUE THREAD

**Issue by Vigneshg98** [wjohnson/pyapacheatlas#165]
@wjohnson  Hi, hope you are doing good.

We face an issue while creating Column Level Process Mapping.

**Source Sample**
```
{
  "Type": [
    {
      "Id": "",
      "Name": ""
    }
  ],
  "Department": [
    {
      "Id": "",
      "Name": ""
    }
  ]
}

```
```
attributeName: Id
qualifiedName: https://****/colls/Test#__tabular_schema//Type:json/-/Id

attributeName: Id
qualifiedName: https://****/colls/Test#__tabular_schema//Department:json/-/Id
```

**Scenario**
Say, we have a column name TypeId in the target. We need to map TypeId to Id field inside an array object Type in the source. If we provide column mapping as given below. It creates mapping with any Id present in the scanned schema.

```
"ColumnMapping": [
    { "Source": "TypeId", "Sink": "Id" }
  ]
```

**Expected Behaviour**
The Id should be mapped to Type -> Id. 
Is there any way we can include the qualifiedName in column mapping?

**Comment by wjohnson** [comment]
Hi, @Vigneshg98 Thank you for using the PyApacheAtlas package!

Did you look at the sample for column mapping?
https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/create_column_mapping_lineage.py#L66:L95

You must include a DataSet mapping as part of the column mapping object / string that IS the qualified name of the source dataset.  I'm not sure what it will look like for tabular schemas though.  You should first try the qualified name of the input and output data sources.  If that doesn't work, try the tabular schema's qualified name.

**Comment by wjohnson** [comment]
@Vigneshg98 - Can you share a more complete example of the issue?  I'm assuming you're building this programmatically so you have complete control over the values you provide to the column mapping, right?

The ColumnMapping Source and Sink are _**free text**_ meaning you can provide ANYTHING you want in there.

Here's an example based off of the sample I shared. Is this what you're looking to accomplish?
![image](https://user-images.githubusercontent.com/1058199/133465855-24d1b80b-99c7-4eca-8f44-6c4d7dc5a1f9.png)

Here's the code for it minus the imports. In each column that you map, you can point from one free text source to one free text sink. The Purview Column Mapping UI does not support the concept of a single table having multiple columns named the same. You would need to distinguish them in some way. For example, maybe `type.id` maps to `id` but `Department.id` maps to `Department`?

```python
procType = EntityTypeDef(
    "ProcessWithColumnMapping",
    superTypes=["Process"],
    attributeDefs = [
        AtlasAttributeDef("columnMapping")
    ]
)

# Upload the type definition
type_results = client.upload_typedefs(entityDefs=[procType], force_update=True)
print(json.dumps(type_results,indent=2))

# Now we can create the entities, we will have two inputs and one output
colMapInput01 = AtlasEntity(
    "Input for Column Mapping",
    "DataSet",
    "https://****/colls/TestINPUT",
    guid=gt.get_guid()
)

colMapOutput01 = AtlasEntity(
    "Output for Column Mapping",
    "DataSet",
    "https://****/colls/TestOUTPUT",
    guid=gt.get_guid()
)

# Now we can define the column mapping object that will be 'stringified'
# and given to our process entity
column_mapping = [
    # This object defines the column lineage between input01 and output01
    {
        "ColumnMapping": [
            {"Source": "Type.Id", "Sink": "id"},
            {"Source": "Department.Id", "Sink": "Department"}
        ],
        "DatasetMapping": {
            "Source": "https://****/colls/TestINPUT",
            "Sink": "https://****/colls/TestOUTPUT"
        }
    }
]

# Create the process with the stringified column mapping json.
process = AtlasProcess(
    name="test process",
    typeName="ProcessWithColumnMapping",
    qualified_name="mysimpleprocwithmapping",
    inputs=[colMapInput01],
    outputs=[colMapOutput01],
    guid=gt.get_guid(),
    attributes={"columnMapping": json.dumps(column_mapping)}
)

results = client.upload_entities(
    [process, colMapInput01, colMapOutput01]
)

print(json.dumps(results, indent=2))
sink_guid = results["guidAssignments"][str(colMapOutput01.guid)]
print(
    f"Search for \"{colMapOutput01.name}\" or use the guid {sink_guid} to look up the sink table.")
exit()
```

**Comment by Vigneshg98** [comment]
@wjohnson  Thank you for your swift response. 
I have added more details/samples for this question. Hope this helps.

Case 1:
```
{
    "Addresses": [
        {
            "Country": {
                "Id": ""
            }
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/30794187/133543822-ac9abe22-96f5-4a37-b62d-6c4880632b06.png)


Case 2:
```
{
    "CareTakers": [
        {
            "Title": {
                "Id": ""
            }
        }
    ]
}
```


![image](https://user-images.githubusercontent.com/30794187/133544083-627732e7-69df-41ce-86a7-44a6c1d95433.png)


Scanned Asset Schema:
```
{
    "Addresses": [
        {
            "Country": {
                "Id": ""
            }
        }
    ],
    "CareTakers": [
        {
            "Title": {
                "Id": ""
            }
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/30794187/133544577-b41bd2be-baf3-419d-8b1c-38d720685640.png)



Here, when we scan the asset, the columns inside Array of Objects are not represented with their Parent relation. Like, Addresses.Country.Id 
The **parent.child** is mentioned only in case of normal JSON i.e, not inside an Array.

Hence while we create Column Mapping Lineage, we are unable to differentiate between Country.Id and Title.Id, since they are just **Id** in the Purview scanned schema.

To solve this, I guess, either we need to get support for Array Object to be scanned properly with Parent-Child relation in Purview OR some way to represent the Lineage mapping along with column level qualifiedName in Column Mapping, like how we provide qualifiedName for the Dataset.

Expected Sample:
```
[
  {
    "ColumnMapping": [
      {
        "Source": "Id",
        "Sink": "CountryId",
        "SourceQualifiedName": "https://****#__tabular_schema//Addresses:json/-/Country/Id",
        "SinkQualifiedName": "https://****#__tabular_schema//CountryId"
      },
      {
        "Source": "Id",
        "Sink": "TitleId",
        "SourceQualifiedName": "https://****#__tabular_schema//CareTakers:json/-/Title/Id",
        "SinkQualifiedName": "https://****#__tabular_schema//TitleId"
      }
    ],
    "DatasetMapping": {
      "Source": "https://****/colls/****",
      "Sink": "https://****/colls/****"
    }
  }
]
```

It would be of great help if you could propose a better solution for this.

**Comment by wjohnson** [comment]
@Vigneshg98 Why don't you just edit the source name for this column? It's free form text and does not have to match an actual column name. You could map a column named orange to banana and it would show up as long as the dataset mapping matched an input and output on the process entity.

```
[
  {
    "ColumnMapping": [
      {
        "Source": "Country.Id",
        "Sink": "CountryId",
      },
      {
        "Source": "Title.Id",
        "Sink": "TitleId",
      }
    ],
    "DatasetMapping": {
      "Source": "https://****/colls/****",
      "Sink": "https://****/colls/****"
    }
  }
]
```

**Comment by wjohnson** [comment]
@Vigneshg98  and I connected offline. The above solution works from a technical standpoint but isn't exactly what his team is looking to accomplish with Purview. Unfortunately, I don't have any control over the official product's roadmap 😅
