### ISSUE TITLE
"delete_entity" method is limiting the deletion of only ~ 120 elements at a time

### ISSUE THREAD

**Issue by richardsonbq** [wjohnson/pyapacheatlas#166]
We're facing a challenge when trying to bulk delete GUIDs from Azure Purview using "delete_entity(guids)" method. In sum, we can not provide lists greater than 100 elements.

This is a big issue when we need to delete several items. For example, we're trying to bulk delete more than 4 Million items and this may take several days to complete if we don't use parallel processing techniques.

Succesful deletion (~ 100 items):

![image](https://user-images.githubusercontent.com/19608343/133614433-47644d10-bce6-4c82-ba07-f94f5ac42601.png)

Parse error when trying to delete more than 120 items:
![image](https://user-images.githubusercontent.com/19608343/133617385-5f7a0be1-2769-4361-9c81-f07dc27cf087.png)

**Comment by wjohnson** [comment]
Hi @richardsonbq - Thank you for using the PyApacheAtlas package!

This is a Purview / Atlas limitation. There are a few potential workarounds:

* Doing some multithreading to call the delete method as you hinted at.
* If you're just clearing out the catalog, you might delete the Purview service itself and re-build it.
* Depending on your type definitions and relationships, you might be able to delete a high level entity that has COMPOSE relationships to other entities.
    * For example, if you delete an Azure SQL Table, it will also delete its child columns because of the relationship type definition.
    * You might investigate whether certain types you are deleting are interrelated in such a way.

**Comment by richardsonbq** [comment]
Thanks, Will! I'm trying to clean up AWS S3 entities from a full load that we have done as part of a Private Preview in our main account. Therefore, creating a new one is not an option right now.
I haven't checked yet whether the deletion of the compose relationships actually works for S3, but definitely will check on that. Either way, the multithreading strategy is working fine (even not being the most effective one).

Thank you!
