### ISSUE TITLE
Create New Collection Under Account Name & Assign it to an Entity

### ISSUE THREAD

**Issue by ravigit94** [wjohnson/pyapacheatlas#167]
Hello,

 I would like to create a new collection and assign it to an existing entity via available functions. Could you please advise if there is a way to do it.

I tried reading collection ID from an existing entity and try assigning it to an existing entity as:

aentity = AtlasEntity(
            description="Country Dimension Table",
            name="DIM_COUNTRY",
            qualified_name="mssql://dev-server-xxxx.database.windows.net/DB_EMPLOYEE/DIMENSION/DIM_COUNTRY",
            typeName="azure_sql_table",
            guid=table_guid,
            collectionId=<collectionID>
                                  )

But it doesn't work.

Thank You

**Comment by wjohnson** [comment]
@ravigit94 - Is this a supported thing in Purview in general?

To test it, try something like this:

```python
adict = aentity.to_json()
adict["collectionId"] = "someCollectionId"

client.upload_entities([adict])
```

If that succeeds, I can add that parameter to the AtlasEntity itself in the next release.

**Comment by ravigit94** [comment]
Thank You for your response. Collections are supported by Purview to group related entities together. By default, if we use upload entities function, it creates an entity under the root account. So we need a way to create an entity in a certain collection under the root account. 

Purview supports:

 1) Creation of hierarchy of a collection (i.e ACCOUNT_PURVIEW (root account) -> Customer -> Internal Customer)
 2) Create an entity under a given hierarchy when scan takes place.
 3) Move an existing entity to a different collection hierarchy .

In order to try what you suggested, I read collection ID from an existing entity using get entity function as:

entities': [{
            'typeName': 'azure_sql_table',
            'attributes': {
                'owner': None,
                'modifiedTime': 1631746587000,
                'replicatedTo': None,
                'replicatedFrom': None,
                'createTime': 1631746587000,
                'qualifiedName': 
 'mssql://xxxxx.database.windows.net/customer/operation/order',
                'name': order',
                'description': None,
                'principalId': 0,
                'objectType': 'U '
            },
            'lastModifiedTS': '2',
            'guid': '90a4b644-f7e3-4463-b902-69f6f6f60000',
            'status': 'ACTIVE',
            'createdBy': 'ServiceAdmin',
            'updatedBy': '9301d476-a86b-49d6-a169-797c9e8bd1d2',
            'createTime': 1631747006621,
            'updateTime': 1631784861439,
           'collectionId': 'ubccon'
}]

Now assigning the same collection ID to a new entity as per your suggestion:
adict = aentity.to_json()
adict["collectionId"] = "ubccon"


client.upload_entities([aentity,col01,col02])

Sadly, **it doesn't work** as I can still see the **root** Purview account assigned to the newly created entity.

**Comment by wjohnson** [comment]
Ah!  I’m guessing there is some extra attribute missing that’s preventing
it from being accepted.

Once it gets documented, maybe then we will know how it works!

**Comment by wjohnson** [comment]
Just to be sure, it looks like your upload points to aentity and not adict.

Could you confirm if you upload adict alone, would it accept the collection
id?

**Comment by ravigit94** [comment]
Thanks for the update.

I have modified the code, but to no avail.

adict = aentity.to_json()
adict["collectionId"] = "ohoj0s"


client.upload_entities([adict,col01,col02])

**Comment by xuky76** [comment]
try through  PUT: /datasources/{dataSourceName}

**Comment by wjohnson** [comment]
@xuky76 - Any hint on the payload / body to be PUT'ed?  That endpoint doesn't appear to be documented anywhere :(

**Comment by xuky76** [comment]
Actually, try this instead sorry


https://docs.microsoft.com/en-us/rest/api/purview/catalogdataplane/collection/create-or-update

**Comment by ravigit94** [comment]
Thank You
