### ISSUE TITLE
Support Collections!

### ISSUE THREAD

**Issue by wjohnson** [wjohnson/pyapacheatlas#173]
https://docs.microsoft.com/en-us/rest/api/purview/catalogdataplane/collection

**Comment by amiket23** [comment]
Any ETA on when collections will be supported?

**Comment by pjtaylor** [comment]
Thanks for the latest update to support this. I'm getting response errors when I try to use it though. e.g.
`results=client.move_entities(guids="[EntityGUID]",collection="[CollectionName]")`
is returning the below. The same parameters work fine with the API call. Am I missing something? list.collections is returning the same so not sure if it is related.

`  File "\Python\Python39\lib\site-packages\pyapacheatlas\core\collections\purview.py", line 203, in move_entities
    results = _handle_response(singleEntityResponse)
  File "\Python\Python39\lib\site-packages\pyapacheatlas\core\util.py", line 378, in _handle_response
    raise ValueError("Error in parsing: {}".format(resp.text))
ValueError: Error in parsing:`

**Comment by wjohnson** [comment]
@pjtaylor `move_entities` requires a list of guids.  Can you try `results=client.move_entities(guids=[ "EntityGUID" ],collection="[CollectionName]")`

I can see the confusion though. I've tried to be as permissive as possible and accept either string or list of strings when the underlying Atlas API actually wants an array of strings.  If you can confirm it's working with `guids = [ "guid" ]` I can look into adding a check for string vs list of strings.

**Comment by pjtaylor** [comment]
Thanks for your response @wjohnson. Tried `results=client.move_entities(guids=[ "54ee5406-1cb6-45e2-b331-7431a76efbd9" ],collection="a5lhlc")`
but getting the same response.

**Comment by wjohnson** [comment]
@pjtaylor  I'm going to close this issue since it's been implemented with the latest release from PyApacheAtlas.  Please let me know if you are still having the problem and we can open a new issue.
