### ISSUE TITLE
Purview atlas endpoint url not matching 

### ISSUE THREAD

**Issue by thec0dewriter** [wjohnson/pyapacheatlas#179]
Hello,
I've tried use the library to connect to a Purview account, but seems that Microsoft might have changed the URL structure.
The library by default uses [ https://{account_name.lower()}.catalog.purview.azure.com/api/atlas/v2](https://github.com/wjohnson/pyapacheatlas/blob/6f038e68bd3dab592cd448083dc70ae6779adb9c/pyapacheatlas/core/client.py#L1499
) while on my Azure Purview account  the catalog url is https://{account_name}.purview.azure.com/catalog 
May I miss something or just Microsoft changed the Purview API?

**Comment by wjohnson** [comment]
Hi there! Thank you for using the package!

Would you mind sharing any error message you are receiving?

**Comment by thec0dewriter** [comment]
Hello,
Sorry, I've figured out that I was requesting actually a wrong entity ID.
