### ISSUE TITLE
Not able to use batch process to upload a process entity referring to existing input and output objects

### ISSUE THREAD

**Issue by MarkCKnutson** [wjohnson/pyapacheatlas#186]
I see in the doc and youtube video that I ought to be able to pass a list of inputs and outputs to the creation of a new process. I have prepared the following code which properly looks up guids for existing objects, but the  batch process returns an error code indicating that the object id is invalid. The error message points to a valid guid for a data source. Is this something that the api supports? If so, please provide an example for this approach. Thanks.
-----------------------------------------------
```python
output_guids = []
input_guids = []

search = client.discovery.search_entities("demoinput01")

for entity in search:
    dict_of_one = {"guid": entity["id"]}
    output_guids.append(dict_of_one)
    
search = client.discovery.search_entities("demooutput01")

for entity in search:
    dict_of_one = {"guid": entity["id"]}
    input_guids.append(dict_of_one)

process = AtlasProcess(
    name="New process",
    typeName="Process",
    qualified_name="custom://newProcess",
    inputs=[input_guids],
    outputs=[output_guids],
    guid="-102"
)

results = client.upload_entities(batch=[process])
```

`atlasException: {"requestId":"d6ca7278-2f79-48d7-80f7-8ed27b9c75a8","errorCode":"ATLAS-400-00-021","errorMessage":"ObjectId is not valid [{guid=***}]"}`

**Comment by wjohnson** [comment]
@MarkCKnutson - Thank you for using PyApacheAtlas!

One problem might be the fact that you have a list of lists being passed to inputs and outputs.

You could try:

```python
process = AtlasProcess(
    name="New process",
    typeName="Process",
    qualified_name="custom://newProcess",
    inputs=input_guids,
    outputs=output_guids,
    guid="-102"
)
```
Since inputs_guids and output_guids are both already lists, you don't need to wrap them in brackets.

**Comment by MarkCKnutson** [comment]
Thank you for your help! that resolved the issue. My mistake here due to newness with the Python language.
