### ISSUE TITLE
Search does not appear to handle wildcard properly

### ISSUE THREAD

**Issue by MarkCKnutson** [wjohnson/pyapacheatlas#187]
I have noticed a number of odd behaviors in the search api including returning results that do not match the search string.  Let's focus on an individual case: I am able to find an object when its name is fully spelled out, but not when there is a wildcard that appears to me should match. Thanks.

search = client.discovery.search_entities("demoinput01") (finds it)

search = client.discovery.search_entities("demoinput0*") (returns zero results)

**Comment by wjohnson** [comment]
Hi, @MarkCKnutson  - Thank you for using PyApacheAtlas!  It looks like the Purview product recently changed their search service.
https://docs.microsoft.com/en-us/azure/purview/how-to-search-catalog#search-query-syntax

I agree, the wildcard does not function the way I would have expected.  I can replicate the issue on my Purview instance.

Not to pass the buck, but this is an Azure Purview service issue and not an issue with PyApacheAtlas.  You might try exploring the new advanced query syntax and see if you can construct a query that fits your need.

**Comment by MarkCKnutson** [comment]
Thankyou for your prompt response. I noted other search issues and I agree the are not caused  by the pyapacheatlas wrapper on the api calls, so closing as resolved.
