### ISSUE TITLE
Need to update contacts on Entities

### ISSUE THREAD

**Issue by amiket23** [wjohnson/pyapacheatlas#198]
We want to update contacts on Entities, could this property be included as a parameter being supplied during entity creation. I see it isn't included currently and is just being returned as false by default.

**Comment by wjohnson** [comment]
Hi, @amiket23  - Thank you for using the PyApacheAtlas package!

A couple questions:
1. Are you targeting Azure Purview or Apache Atlas?
2. Would you be able to share the snippet of code you are using to populate the contacts?

If you use something like this for Azure Purview:

```python
ae =AtlasEntity(
    "myentity",
    "entityFQN",
    guid="-1",
    contacts ={"Expert":[{"id":"aad-id-of-some-user", "info":""}], "Owner":[]}
)
```

You should be able to define the Experts / Owners for Azure Purview.

The contacts parameter is one of the kwarg parameters but it expects you know the definition of the complex object that Azure Purview expects.

**Comment by vjcuadros** [comment]
I'm using this code but looks like it doesnt update it, but when I go to filters in purview I can search it by contacts, not sure if purview bug, when I go to contact on entity it's empty
