### ISSUE TITLE
Unable to Update Schema details (Classification column) into Purview from User defined API.

### ISSUE THREAD

**Issue by karthick-12345** [wjohnson/pyapacheatlas#202]
Hi 
I am using this guide for writing our custom API for doing business operation (update schema details) with PURVIEW. Here we are using Nodejs restify for writing API to interact with PURVIEW.

When we trying to update schema details (particularly Classification field) we are facing issue - **update to classification is not allowed from propagated entity - status code 400**, but we are not sure what are the parameter we are missing while passing as a payload while updating schema details.

Could you guide us or provide information, for updating schema from external API. what are the precheck or prerequisite PURVIEW internal API  consider? so that we can update our API accordingly.

**What have you tried so far?**
I have tried to pass all the required fields as same as what I could see as payload while I upload via  Azure Purview portal. But still not working. 

**Screenshots**
![purview](https://user-images.githubusercontent.com/99859995/167334030-cebcb277-006e-45be-9872-9ccd3c4d5c8d.png)

Regards,
Karthick

**Comment by wjohnson** [comment]
I apologize, Karthick, I'm not sure if you still need some guidance on this. If so, please let me know and we can try to experiment a bit over github.
