### ISSUE TITLE
Request timed out

### ISSUE THREAD

**Issue by EdoMatt** [wjohnson/pyapacheatlas#209]
I want to extract my glossary, more or less 6000 terms. The request for the glossary needs too much time to complete. I tried to set a timeout, like in the picture below, but it doesn't work.

 How can I solve the problem?
![image](https://user-images.githubusercontent.com/101015753/182161367-3609f764-a616-49c4-bf13-0fa17bd6b3a5.png)

**Comment by wjohnson** [comment]
Hi, @EdoMatt ! Thank you for using PyApacheAtlas.  This looks to be a server side issue unfortunately.

Have you considered using the export option instead?  https://wjohnson.github.io/pyapacheatlas-docs/latest/pyapacheatlas.core.html#pyapacheatlas.core.client.PurviewClient.export_terms

The only challenge with this is that you have to coordinate based on Term Templates. You cannot mix two terms from different term templates in the same export.

Alternatively, set `detailed=False` and then you could call each glossary term individually via https://wjohnson.github.io/pyapacheatlas-docs/latest/pyapacheatlas.core.html#pyapacheatlas.core.glossary.GlossaryClient.get_term

Definitely not efficient but you'd certainly avoid the timeout issue.

**Comment by wjohnson** [comment]
Closed, over 30 days with no follow up.
