### ISSUE TITLE
Attach schema to the existing Entity

### ISSUE THREAD

**Issue by edobrynin-dodo** [wjohnson/pyapacheatlas#210]
**What is your desired outcome**
Hello Will & all the contributors!

Is it possible to attach schema to existing entity?
I found some tips in "[pyapacheatlas wiki"](https://github.com/wjohnson/pyapacheatlas/wiki/Azure-Purview-Tips#create-your-own-resource-set), but in those examples we create the entity with schema from scratch.

My case is a little bit different: I already have an Entity with type "azure_datalake_gen2_resource_set" on my Atlas Server, and I would like to attach schema to it, so after the update I would able to see "Schema" tab on Entity's page in Purview.

**What have you tried so far**
I tried to use entity.addRelationship(), but this didn't work unfortunately:

```
ts = AtlasEntity(
        name="demotabschema22",
        typeName="tabular_schema",
        qualified_name="pyapache://demotabschema22",
        guid = -2
    )
    # Create a Column entity that references your tabular schema
    
    col01 = AtlasEntity(
        name="democolumn",
        typeName="column",
        qualified_name="pyapche://mycolumn",
        guid=-3,
        attributes={
            "type":"Blah",
            "description": "blabh blah"
        },
        relationshipAttributes = {
            "composeSchema": ts.to_json(minimum=True)
        }
    )
    

    # The entity with these typeName & qualifiedName already exists on my Atlas server, so I'm trying to update it
    table_ac = AtlasEntity(
        name="silver.p_actual_stock_balance",
        typeName="azure_datalake_gen2_resource_set",
        qualified_name="https://proddatalakedodo.dfs.core.windows.net/deltalake/data/silver/P_ActualStockBalance",
        guid = -2
    )
    
    table_ac.addRelationship(tabular_schema = ts.to_json())
    results = client.upload_entities([table_ac.to_json(), ts.to_json(), col01.to_json()])
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.3.1
 - PyApacheAtlas Version == 0.13.1: 

**Additional context**
Thank you for the great library!
Best regards,
Evgenii

**Comment by wjohnson** [comment]
Hi @edobrynin-dodo ! Thank you for using PyApacheAtlas!

I think the challenge might be a re-use of the guid of "-2"?  I noticed that that same guid was being used in ts and table_ac. That may result in one of the entities being ignored.

I took the liberty of using the `GuidTracker` utility class and adjusting your script.  You don't have to convert everything to json if you're using the latest version of PyApacheAtlas 😁

```python
from pyapacheatlas.core.util import GuidTracker
gt = GuidTracker()
ts = AtlasEntity(
     name="demotabschema22",
     typeName="tabular_schema",
     qualified_name="pyapache://demotabschema22",
     guid = gt.get_guid()
)
# Create a Column entity that references your tabular schema
col01 = AtlasEntity(
    name="democolumn",
    typeName="column",
    qualified_name="pyapche://mycolumn",
    guid=gt.get_guid(),
    attributes={
        "type":"Blah",
        "description": "blabh blah"
     }
)
col01.addRelationship(composeSchema=ts)

# The entity with these typeName & qualifiedName already exists on my Atlas server, so I'm trying to update it
table_ac = AtlasEntity(
    name="silver.p_actual_stock_balance",
    typeName="azure_datalake_gen2_resource_set",
    qualified_name="https://proddatalakedodo.dfs.core.windows.net/deltalake/data/silver/P_ActualStockBalance",
    guid =gt.get_guid()
)
table_ac.addRelationship(tabular_schema = ts)

results = client.upload_entities([table_ac, ts, col01])
```

Would you mind giving this a try?

**Comment by edobrynin-dodo** [comment]
Hi @wjohnson! 

This works great, thank you very much! 🎉🎉🎉

Though I need to take a look at this GuidTracker class closely, not sure how it actually works :/ 
I thought that if we use any negative number as guid it means something like "ignore guid and use typeName + qualifiedName pair to make updates", and it doesn't matter which negative number to use.

Thank you for such a quick reply! 

Best Regards,
Evgenii

**Comment by wjohnson** [comment]
Glad to hear it's working!  The guid tracker is nothing more than a global variable that keeps track of which guid you've already used.  You can definitely provide your own "-1", "-2" but I thought it was really tedious so I added this helper class.

When you run the upload_entities method, you get back a Guid Assignments section in the response.  That section maps "-1" to guid "abc-123-jkl" and guid "-2" to "def-hijk-456".  This is super convenient if you know that guid -1 was some entity you wanted to use immediately after it was committed to Atlas.  But, as you saw, if you have a duplicate guid it's going to ignore one of the dupliates 🙁
