### ISSUE TITLE
Using discovery.search_entities with serviceType

### ISSUE THREAD

**Issue by lukaszpriba** [wjohnson/pyapacheatlas#221]
I am trying to perform a search on the catalogue using the `discovery.search_entities` on serviceType:

`search_service_type_hive = client.discovery.search_entities("serviceType:hive")`
`for entity in search_service_type_hive:`
 `         print(json.dumps(entity, indent=2))`

I get a massive output that is essentially all entities in my catalogue 

OS: Windows
PyApacheAtlas Version: 0.13.1

**Comment by wjohnson** [comment]
Hi, @lukaszpriba - Thank you for using PyApacheAtlas!  I don't believe service type is an option that is included in the search for Microsoft Purview or Apache Atlas?

Service Type is defined on the type def.  However, there is an "assetType" attribute that you can target by using the search filters.

Here's an example using Databricks types:

```python
resp = client.discovery.search_entities("*", search_filter={
    "and": [{
        "attributeName": "assetType",
        "operator": "eq",
        "attributeValue": "Databricks"
    }],
})

for each in resp:
    print(each)
```

Please give that a try with Hive as the attribute value and see if that filters your results further.

**Comment by lukaszpriba** [comment]
Hi @wjohnson, I see. Thanks for the suggestion. I get the same result with a bit simpler statement:

`search_by_entityType = client.discovery.search_entities("entityType:hive_table")` 
*with the exception of differences in @search.score

Either method returns just the hive_table, without any indication of hive_columns underneath it. The only other way of getting that info I can think of is to pass that the guid from the search result into `client.entity()`

**Comment by wjohnson** [comment]
> Either method returns just the hive_table, without any indication of hive_columns underneath it. The only other way of getting that info I can think of is to pass that the guid from the search result into `client.get_entity()`

You've got it.  Unfortunately, Purview search does not currently return column data.  The columns are _indexed_ but their asset information is tied to the table they belong to. As a result, tables that you receive likely contain these columns but you'd have to exactly as you described (take the guid(s), run `client.get_entity([guid1, guid2, ... ])` and investigate the response for the columns).

Please let me know if it's okay to close out the issue given this information.

And thank YOU for sharing the `"entityType:hive_table"` keyword trick!  Very good to know!

**Comment by lukaszpriba** [comment]
Hi @wjohnson, yes this makes sense. Thanks for that, I'm happy with the solution so ticket can be closed
