### ISSUE TITLE
Audits tab doesnt populate when data is uploaded with pyapacheatlas bulk upload

### ISSUE THREAD

**Issue by APOTUC1B** [wjohnson/pyapacheatlas#224]
We are using the below code to upload to atlas from excel

            excel_config = ExcelConfiguration()
           excel_reader = ExcelReader(excel_config)
           entities = excel_reader.parse_bulk_entities(file_name)
           results = client.upload_entities(entities)

upoon upload the Audits tab is empty 
action is empty and there is no entity created action with time stamp

when we specify a clasisfication 
action is Classification Added and time stamp is populated.

please let us know if we need to add any code to have the audit populated always

![test1](https://user-images.githubusercontent.com/89108589/192387068-588c92de-7a68-4ae7-a0fd-ae5c65e6549d.PNG)
![test2](https://user-images.githubusercontent.com/89108589/192387309-ddb11c37-48f3-4b7b-8381-c6139fc02fa0.PNG)

**Comment by wjohnson** [comment]
Thank you for using PyApacheAtlas!

Can you point to a doc on Atlas that says the audit tab is populated on /entity operations?

From this doc (https://docs.cloudera.com/cdp-private-cloud-base/7.1.8/atlas-audit/atlas-audit.pdf) it looks like only import / export operations are audited but not individual or bulk asset creation.

Does that match what you are seeing?

**Comment by APOTUC1B** [comment]
but i creates audit entry some time and it doesnot some times sing bulk upload .attached screen shot 
not sure why and how it does.

<img width="661" alt="test3" src="https://user-images.githubusercontent.com/89108589/192578274-0410315c-78e4-4cde-8d39-bb034adde7e7.PNG">

**Comment by APOTUC1B** [comment]
this issue is coming because of ranger authorization .audits works for non ranger authorization

**Comment by APOTUC1B** [comment]
this issue is coming because of ranger authorization .audits works for non ranger authorization

issue can be closed

**Comment by wjohnson** [comment]
Glad you got it figured out! Thank you for sharing what you found.
