### ISSUE TITLE
SSLError with PurviewClient

### ISSUE THREAD

**Issue by marjan-radfar** [wjohnson/pyapacheatlas#226]
I am using PurviewClient to connect to Purview from Databricks. I didn't have any problem reading assets, however, I am facing this issue since today:

`SSLError: HTTPSConnectionPool(host='<purview_account_name>.purview.azure.com', port=443): Max retries exceeded with url: /catalog/api/atlas/v2/entity/bulk?guid=<sample_guid>&ignoreRelationships=False&minExtInfo=False (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1131)')))`

Can you please help me with resolving this issue?

**Comment by wjohnson** [comment]
Hmm.. This is something specific to the requests package and your network setup.

You can try following the steps in #191 to requests requests_verify = False on your Purview Client setup.

Alternatively, it looks like there are a few suggestions on StackOverflow: https://stackoverflow.com/questions/41780517/python-ssl-error-decryption-failed-or-bad-record-mac

**Comment by marjan-radfar** [comment]
> Hmm.. This is something specific to the requests package and your network setup.
> 
> You can try following the steps in #191 to requests requests_verify = False on your Purview Client setup.
> 
> Alternatively, it looks like there are a few suggestions on StackOverflow: https://stackoverflow.com/questions/41780517/python-ssl-error-decryption-failed-or-bad-record-mac

Thanks @wjohnson for your prompt reply. I added requests_verify = False argument to my PurviewClient but didn't help. Is there any limitation on the number of requests using Purview REST API?

**Comment by marjan-radfar** [comment]
I am also getting this error:
`SSLError: HTTPSConnectionPool(host='<purview_account_name>.catalog.purview.azure.com', port=443): Max retries exceeded with url: /api/browse?api-version=2022-03-01-preview (Caused by SSLError(SSLError(1, '[**SSL: WRONG_VERSION_NUMBER**] wrong version number (_ssl.c:2635)')))`

**Comment by wjohnson** [comment]
> WRONG_VERSION_NUMBER
Try this out? https://stackoverflow.com/questions/65516325/ssl-wrong-version-number-on-python-request

When creating the PurviewClient pass in `requests_verify=False` and `requests_proxies=proxies` after defining what proxies you are using.

**Comment by marjan-radfar** [comment]
> > WRONG_VERSION_NUMBER
> > Try this out? https://stackoverflow.com/questions/65516325/ssl-wrong-version-number-on-python-request
> 
> When creating the PurviewClient pass in `requests_verify=False` and `requests_proxies=proxies` after defining what proxies you are using.

Thank you very much @wjohnson for your kind help.

**Comment by wjohnson** [comment]
Closing this out as it looks to be complete and no further updates for over a month.  Please feel free to open again if there are additional questions.
