### ISSUE TITLE
get_term throws KeyError:'terms' if the Glossary is empty

### ISSUE THREAD

**Issue by adinastoll** [wjohnson/pyapacheatlas#233]
**Describe the bug**
[get_term](https://github.com/wjohnson/pyapacheatlas/blob/7fbc0ae3b3c661db07a443306995d4c416a01e1a/pyapacheatlas/core/glossary/glossaryclient.py) function throwns an exception if the Glossary is empty

**Stack trace**
[2022-11-28T10:26:09.886Z]   File ".venv/lib/python3.9/site-packages/pyapacheatlas/core/glossary/glossaryclient.py", line 135, in get_term
[2022-11-28T10:26:09.886Z]     for term in terms_in_glossary["terms"]:
[2022-11-28T10:26:09.886Z] KeyError: 'terms'

**Expected behavior**
No exception is thrown if the Glossary is empty. None is returned.

**Screenshots**
Check that the key exists before trying to access it
![image](https://user-images.githubusercontent.com/6609080/204837169-8543560e-eee8-41ee-81a2-35d32b76a328.png).

**Desktop (please complete the following information):**
 - OS:  Windows
 - PyApacheAtlas Version (`python -m pyapacheatlas --version`): 0.14.0

**Comment by wjohnson** [comment]
Thank you SO Much, @adinastoll for reporting this issue!  I will try to knock out a fix for it this weekend!
