### ISSUE TITLE
Excel Custom type with columns

### ISSUE THREAD

**Issue by grendo** [wjohnson/pyapacheatlas#234]
Do you have an example of loading a custom type with columns and associated entity using the excel template, (I am using purview) ?

This works for azure_sql_table
typeName,name,qualifiedName,description,userDescription,[Relationship] table,data_type
azure_sql_table,mtab2,pyapacheatlas://mtab2,desc2,user desc2,,
azure_sql_column,col1,pyapacheatlas://mtab2#col1,col1 desc,col1 user desc,pyapacheatlas://mtab2,string

If I create a custom type with a super type of azure_sql_table, (MyAzureSqlTable) the following crashes on the azure_sql_column.  There is no help in the exception message.

typeName,name,qualifiedName,description,userDescription,[Relationship] table,data_type
MyAzureSqlTable,mtab2,pyapacheatlas://mtab2,desc2,user desc2,,
azure_sql_column,col1,pyapacheatlas://mtab2#col1,col1 desc,col1 user desc,pyapacheatlas://mtab2,string

**Comment by grendo** [comment]
I followed through the code at https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/create_type_with_schema.py and compared what is happening when I load via the excel spreadsheet.  It appears that the spreadsheet is not setting up the relationship between the custom type and the column as I do not see anything under related assets on the purview properties screen of the entity.

**Comment by wjohnson** [comment]
Coming up on a month with no comment.  Please let me know if there is anything you still need.
