### ISSUE TITLE
Unable to connect to the Purview using Service Principal

### ISSUE THREAD

**Issue by ujvalgandhi1** [wjohnson/pyapacheatlas#236]
I am following the instructions laid out in the Service Principal route but am getting a 
requests.exceptions.RequestException: {"error":{"code":"Unauthorized","message":"Not authorized to access account"}}

error

I did follow the instructions laid out in the Service Principal route at https://learn.microsoft.com/en-us/azure/purview/tutorial-using-rest-apis and was able to verify that I got an access token back.

Can someone please assist me?

Ujval Gandhi

**Comment by ujvalgandhi1** [comment]
Fixed the issue - had to do with clearing out the browser cache multiple times

**Comment by wjohnson** [comment]
Glad you were able to resolve it!
