### ISSUE TITLE
How do i create an Enumeration with the API

### ISSUE THREAD

**Issue by adamjburgess** [wjohnson/pyapacheatlas#244]
I was wondering if there is a way using the API to create an Enumeration that I can then assign to Business Metadata. 

I can manually create the Enumeration in the Atlas Admin Portal  and assign it the Business Meta Data Attribute using the api, but i want to create the enumeration with the api if possible.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PyApacheAtlas Version (`python -m pyapacheatlas --version`):  0.14.0

**Comment by wjohnson** [comment]
Thanks for using the PyApacheAtlas package!  Enumerations are just another TypeDef!

https://atlas.apache.org/api/v2/json_AtlasEnumDef.html

In PyApacheAtlas, I don't provide a pre-built class for it (no one has asked for one yet!)

You could either build up the JSON yourself following the above link or used `[BaseTypeDef](https://wjohnson.github.io/pyapacheatlas-docs/latest/core/api/pyapacheatlas.core.typedef.BaseTypeDef.html)` and add the necessary properties given Python object.  

Finally submit it via `client.upload_typedefs(enumDefs=[yourEnumDef])`.

I hope that helps!
