### ISSUE TITLE
How to programmatically add tags?

### ISSUE THREAD

**Issue by mikeweltevrede** [wjohnson/pyapacheatlas#245]
**What is your desired outcome**
~~I would provide a list of strings which would be added as tags with the same functionality as this UI action: https://learn.microsoft.com/en-us/azure/purview/catalog-asset-details#add-a-tag-to-an-asset. This way, we can filter on them in the browse view here:~~

**EDIT**: I found that we can use `pyapacheatlas.core.client.PurviewClient.update_entity_labels()`. This was unclear to me since Labels are also another term within Purview. Perhaps the name should be updated?

**What have you tried so far**
- Google for options. Labels and Assigned Terms are not the same. On the MS website, only the UI option is mentioned.
- File an issue on the Azure Purview documentation: https://github.com/MicrosoftDocs/azure-docs/issues/108968

**Screenshots**
See screenshot of desired outcome here: https://learn.microsoft.com/en-us/azure/purview/catalog-asset-details#add-a-tag-to-an-asset

**Desktop (please complete the following information):**
 - OS: Windows
 - PyApacheAtlas Version (`python -m pyapacheatlas --version`): 0.15.0

**Additional context**
N/A

**Comment by wjohnson** [comment]
Thanks for this feedback, @mikeweltevrede !  I think adding a facade method that follows the Purview naming conventions would prevent others from having the same question.  I'll work to add this into the next version!
