### ISSUE TITLE
About create a bulk upload and update approach using Excel for "managed attributes" in MS Purview

### ISSUE THREAD

**Issue by cek012** [wjohnson/pyapacheatlas#247]
**What is your desired outcome**
My client scanned some data in MS Purview. I and my team need to update the lost information on MS Purview. One of them is the Managed attributes. I know pyapacheatlas can update the information in a JSON file under the key name "Entities". But the Managed attributes are under the referredEntities. I wonder if it is possible to use pyapacheatlas to update Managed attributes. If not, can you please tell me if is there another way to do it?

**What have you tried so far**
Search the api list and find out if there has a way to update referredEntities? But I don't think so.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PyApacheAtlas Version (`python -m pyapacheatlas --version`): 0.15.0

**Additional context**
N/A

**Comment by wjohnson** [comment]
Hi, @cek012 thank you for using PyApacheAtlas!  My understanding is that you would need to update the existing entities via the other API endpoints.

See the [sample here](https://github.com/wjohnson/pyapacheatlas/blob/f5fa20c8042b019b670d32542c068f558ed0d9e9/samples/CRUD/crud_business_metadata.py) (called business attributes in Apache Atlas) specifically lines 64-69.

I would iterate over the referred entities (they should have guids as the key or embedded in them I believe) and then call the `client.update_businessMetadata` method on each of them.

**Comment by wjohnson** [comment]
Closing this out but please feel free to reopen if you need additional guidance / support.
