### ISSUE TITLE
Uploading an entity to a sub collection, instead of the root collection.

### ISSUE THREAD

**Issue by MickeyLulz** [wjohnson/pyapacheatlas#248]
**What is your desired outcome**
Be able to upload / bulk upload new entities to a sub collection. As of now I can only create the new entities in the root collection.

**What have you tried so far**
Looked through the documentation (https://github.com/wjohnson/pyapacheatlas) but have not found anything that can do this.

**Screenshots**
This is what my collections look like. I want to be able to create new entities in the sub collections under my root collection (ie. be able to create an entity in 'Snowflake_Economics').
![image](https://github.com/wjohnson/pyapacheatlas/assets/17971488/966a629a-3ecc-4edc-a726-5cc7b7d4ed09)

**Desktop (please complete the following information):**
 - OS: Windows
 - PyApacheAtlas Version (`python -m pyapacheatlas --version`): 0.15.0

**Additional context**
Is there also a list of type names? This would be quite helpful with creating new entities.

**Comment by wjohnson** [comment]
Hi, @MickeyLulz Thank you for using PyApacheAtlas!

To answer your maing question, you can use `client.collections.upload_entity()` where you must specify the collection id.

[Doc](https://wjohnson.github.io/pyapacheatlas-docs/latest/core/collections.html)
[Small Sample](https://github.com/wjohnson/pyapacheatlas/blob/f5fa20c8042b019b670d32542c068f558ed0d9e9/tests/integration/smoke_post_calls.py#L239-L241)

To get the collection id you probably will need to [list all of the collections](https://wjohnson.github.io/pyapacheatlas-docs/latest/core/api/pyapacheatlas.core.collections.PurviewCollectionsClient.list_collections.html)

To answer your additional context question, you can use [get_all_typedefs](https://wjohnson.github.io/pyapacheatlas-docs/latest/core/client/api/pyapacheatlas.core.client.PurviewClient.get_all_typedefs.html) to list all of the typedefs in your purview instance.

Please let me know if that helps!

**Comment by wjohnson** [comment]
Closing but please feel free to re-open if you need any additional guidance.
