### ISSUE TITLE
what is typename for parquet, csv and parquet resource set

### ISSUE THREAD

**Issue by KarthikATOS22** [wjohnson/pyapacheatlas#249]
Is this right forum for Q&A, pls advise.

Is it possible to create lineage for files viz, parquet, csv, parquet resource set. if yes, pls help me find typename for parquet, csv and especially resource set 

Tried creating lineage between Azure SQL Table and CSV file using UpdateLineage tab with default excel template.
Error Message:  
pyapacheatlas.core.util.AtlasException: {"requestId":"5df20c41-fea0-4300-9d53-7e15509b251d","errorCode":"ATLAS-404-00-00A","errorMessage":"Referenced entity AtlasObjectId{guid='null', typeName='**delimited_text_schema**', uniqueAttributes={qualifiedName:https://adlsXXXX.dfs.core.windows.net/fileformats/SalesOrderHeader-CSV.csv}} is not found"}

**Comment by ptinsl** [comment]
There is no typeName for parquet or csv. It depends where it is saved. If it is stored in a ADLS storage account, it will typically be azure_datalake_gen2_resource_set. 

To find out definitively, you will have to find the definition of the Asset. This can be done by using this package and calling this method.
https://wjohnson.github.io/pyapacheatlas-docs/latest/core/client/api/pyapacheatlas.core.client.PurviewClient.get_entity.html#pyapacheatlas.core.client.PurviewClient.get_entity

The GUID can be found from the URL when you are logged in to purview and you are on the asset overview page of the specific asset.

**Comment by wjohnson** [comment]
Thank you @ptinsl for answering the question!!   @KarthikATOS22 please let us know if you have any other questions or concerns.
