### ISSUE TITLE
Support for user requests (Azure Purview)

### ISSUE THREAD

**Issue by Freds72AtWork** [wjohnson/pyapacheatlas#250]
**Proposal**
Add support to submit a change as a 'workflow request' for Azure Purview
The goal is to ensure API requests are going through the integrated Purview workflow engine.

**Example**
An automated system compares a database against glossary terms and upload missing entities/term to Purview.
The new entries are not immediately available in the system but goes through a validation process.

**Issues that this feature solves**
N/A

**Suggested Implementation**
See: https://learn.microsoft.com/en-us/rest/api/purview/workflowdataplane/submit-user-requests/submit-user-requests?tabs=HTTP

**Comment by wjohnson** [comment]
Hi, @Freds72AtWork Thank you so much for using PyApacheAtlas!  The scope of this package is strictly the data catalog portion of Purview and Apache Atlas.  If you are interested in automating the workflow creation process, you might consider the [azure-purview-workflow](https://learn.microsoft.com/en-us/python/api/azure-purview-workflow/azure.purview.workflow.aio.purviewworkflowclient?view=azure-python-preview#azure-purview-workflow-aio-purviewworkflowclient-submit-user-requests) package instead.
