### ISSUE TITLE
create or update scans

### ISSUE THREAD

**Issue by Kevin-McIsaac** [wjohnson/pyapacheatlas#251]
**Describe the feature**
Now that we can add collections it would be helpful to be able to add, update or delete Scans.

**Comment by wjohnson** [comment]
Hi, @Kevin-McIsaac thank you so much for using PyApacheAtlas!  The scope of this package is limited to the data catalog portion of Purview.  If you're interested in scanning, you might consider using the [azure-purview-scanning](https://learn.microsoft.com/en-us/python/api/azure-purview-scanning/?view=azure-python-preview) package in addition to PyApacheAtlas.
