### ISSUE TITLE
parse_bulk_entities code

### ISSUE THREAD

**Issue by Sgidwani61** [wjohnson/pyapacheatlas#252]
I am using the parse_bulk_entities code to upload excel files to purview and including the owners and experts column. However, something weird i noticed is that the code refers to an old branch for some reason. When i make the upload_entities call passing in the cont_func , i get this error:

    317             contacts_cache = {}
    318             contacts_func = contacts_func or (lambda x: x)
--> 319             if ("experts" in row or "owners" in row) and len(row.get("experts", "") + row.get("owners", "")) > 0:

which looks like its from a different branch of the code.. not sure if there is a way you specify using the master branch only but thought this was interesting and was wondering if you had any fixes/suggestions

**Comment by Sgidwani61** [comment]
ahh it looks like this update to the code was pushed on feb 23 after the latest release on feb 17! Is there any way you can push the latest code in a release?

**Comment by wjohnson** [comment]
@Sgidwani61 Ah!  Thank you for calling this out and thank you for using PyApacheAtlas!  This release slipped a while back and I will be looking to push out a release by early next week.  I'll comment back here as soon as that release is complete.

**Comment by Sgidwani61** [comment]
Awesome thank you! One other question... im trying to basically extract all the schema data from a given entity by iterating through all the entities in a collection and extracting all the metadata to an excel file, entering in the column descriptions/owners/experts etc. from this excel and then calling the parse bulk entities to upload the excel and just make the manual process of entering in all that information a bit more easy. I want to do the same thing for classifications and glossary terms/sensitivity labels... i know you have to use different endpoints for those if the entities are already created in purview..

do you have to write basically a completely different function passing in all of the guids for the column metadata for example to the classify entity? like is there no way to do it through extracting that information to the excel and reuploading it ? 

Also, would this only work for system default classifications or does it also work for custom classifications?

Apologies for the lengthy question!

**Comment by wjohnson** [comment]
Hi, @Sgidwani61 would you be able to give me an example?

It sounds like you're trying to do the following:

* Call the get_entity method and get one or many entities from Atlas / Purview
* Convert the results json to Excel in the right format for bulk upload
* Allow a user to open an excel file and edit the content
* Upload the content

One of the challenges you'll have is that things like classifications and labels/tags cannot be updated with the /entity endpoint.

I lightly document the capabilities of the excel portion here: https://datasmackdown.com/oss/pyapacheatlas/excel/bulk-upload.html  For NEW entities you don't need to do anything else.

For EXISTING entities you'll need some other methods to update things:

https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/create_entity_and_classification.py

https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/crud_business_metadata.py

https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/crud_custom_attributes.py

https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/crud_custom_labels.py

I hope that helps!  Please let me know if I misunderstood your question.

**Comment by wjohnson** [comment]
@Sgidwani61 again, thank you for your patience.  I just published release 0.16.0 which has the fix in it.  Thank you for your continued use of PyApacheAtlas!
