### ISSUE TITLE
How do I update columns from a given entity on Purview?

### ISSUE THREAD

**Issue by guimatheus92** [wjohnson/pyapacheatlas#253]
**What is your desired outcome**
I was successful by updating description for a given entity on Purview (in my case is a Kusto table). I am also trying to update each column description also, that way I could have all information in place for our users.

**What have you tried so far**
The way I did was:

1. Used the `get_by_guid()` function to retrieve all information I have and understand the response. So I saw that every column description is under the `referredEntities` dict.
2. Same query I used to update the entity description, I tried with `create_or_update()` function but despite the message is not retrieving any error, the descriptions is not being updated also.
3. My query:

``` python
# Define the keywords and updated description
updated_description = "New description for the asset"

# Create the entity input with the updated description
entity_input = {
  "referredEntities": {
        "typeName": "azure_data_explorer_column",
        "attributes": {                
                "qualifiedName": "https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest#ID_VM",
                "name": "ID_VM",
                "description": updated_description,
                "userDescription": "<div>VM Id</div>",
            },
      },
  "entity": {
    "typeName": "azure_data_explorer_table",
    "attributes": {
      'qualifiedName': 'https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest',
      'name': 'DimensionDevicesTest', 
    }
  }  
}

try:
    # Call create_or_update to update the asset
    response = client_catalog.entity.create_or_update(entity=entity_input)
    print("Asset updated successfully:", response)
except HttpResponseError as e:
    print("Error updating asset:", e)
```
This the output of query above:

`Asset updated successfully: {'guidAssignments': {'-271567942211068': 'f31eeb6a-d9b0-48d3-a461-f9f6f6f60000'}}`

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise, version 22H2, build 22621.2134
- I am not using PyApacheAtlas library, I am using azure-purview-catalog to update my data

**Additional context**
The query that is working and that I am using to update my entity description is this one:

``` python
# Define the keywords and updated description
updated_description = "New description for the asset"

# Create the entity input with the updated description
entity_input = {
  "referredEntities": {},
  "entity": {
    "typeName": "azure_data_explorer_table",
    "attributes": {
      'qualifiedName': 'https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest',
      'name': 'DimensionDevicesTest', 
      "userDescription": updated_description,
    }
  }
}

try:
    # Call create_or_update to update the asset
    response = client_catalog.entity.create_or_update(entity=entity_input)
    print("Asset updated successfully:", response)
except HttpResponseError as e:
    print("Error updating asset:", e)
```

**Comment by wjohnson** [comment]
HI, @guimatheus92  just to be clear, this is the Github repo for PyApacheAtlas, and not the Azure-Purview-Catalog package.

I'd encourage you to use PyApacheAtlas instead ;-)

However, to answer your question, you should create an array/list of column entities you want to update.  You should not place any updates in the referred entities section.  Your end result should look like your second block of code just with the `azure_data_explorer_column` instead.

```python
# Define the keywords and updated description
updated_description = "New description for the asset"

# Create the entity input with the updated description
entity_input = {
  "referredEntities": {},
  "entity": {
    "typeName": "azure_data_explorer_column",
        "attributes": {                
                "qualifiedName": "https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest#ID_VM",
                "name": "ID_VM",
                "description": updated_description,
                "userDescription": "<div>VM Id</div>",
            }
  }
}

try:
    # Call create_or_update to update the asset
    response = client_catalog.entity.create_or_update(entity=entity_input)
    print("Asset updated successfully:", response)
except HttpResponseError as e:
    print("Error updating asset:", e)
```

Sometimes you have to specify a required attribute or relationship attribute.  In this case, it looks like the `table` relationship attribute is required and the `data_type` attribute is required.  Your entity_input payload may have to look like this instead.


```python
entity_input = {
  "referredEntities": {},
  "entity": {
    "typeName": "azure_data_explorer_column",
        "attributes": {                
                "qualifiedName": "https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest#ID_VM",
                "name": "ID_VM",
                "data_type": "string",
                "description": updated_description,
                "userDescription": "<div>VM Id</div>",
            },
        "relationshipAttributes": {   
                "table": {
                    "typeName": "azure_data_explorer_table", 
                    "uniqueAttributes": {
                        'qualifiedName': 'https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest'
                }
            },
    }
}
```

I hope this helps.  You may have to go through Microsoft official channels to get a more complete answer if this isn't what you're looking for.

**Comment by wjohnson** [comment]
Closing this out but please feel free to reopen if you need additional guidance!
