### ISSUE TITLE
How to  filter entities based on their Power BI Workspace?

### ISSUE THREAD

**Issue by JavaPr288** [wjohnson/pyapacheatlas#255]
**I am working with Power BI entities in Azure Purview using the Apache Atlas Python library. I want to filter the entities based on the name of the Power BI workspace they belong to. How can I use the API to get the workspace name for each entity?**

Would this be the best way to do it?
To get the Power BI workspace name for each entity, you can use the `get_entity_by_attribute` or `get_entity_by_guid` methods of the `PurviewClient` class from the `pyapacheatlas` package. 
The workspaceName attribute is a custom attribute added by Azure Purview to the Power BI entities. You can access it by using the `entity.attributes['workspaceName'] `syntax.
The attribute is not technically part of the Library but should still be accessible.
Library is very cool!
Thanks

**Comment by wjohnson** [comment]
Hi, @JavaPr288 !  Thank you for using PyApacheAtlas!

Can you share how you're getting the list of entities in the first place?

If you're just looking to access workspaceName, then the path you chose is the right way.  The Apache Atlas spec declares attributes a map/dict and I'm not as fancy as pandas to make attribute properties accessible like `entity.attributes.workspaceName` although it does look really slick!

Alternatively, if you're just trying to filter them down, I'd do it in one of two ways:

## Search

You might be using [search](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/read_search_by_name.py) so you should be able to apply a [filter](https://learn.microsoft.com/en-us/rest/api/purview/catalogdataplane/discovery/query?tabs=HTTP#discovery_query_attribute)?

```python
filter_setup = {
    "and": [
        {
        "attributeName": "workspace",
        "operator": "eq",
        "attributeValue": "myworkspace"
        }
    ]
}
search = client.discovery.search_entities("*", search_filter=filter_setup)
```

## List of Entities

Assuming you've got an actual list of entity objects, you could just use a list comprehension.

```python
wksp_name = "myworkspace"
 [e for e in entities if e.attributes.get("workspace", None) == wksp_name]
````

I hope that helps!

**Comment by JavaPr288** [comment]
Hi,
Thanks for your quick response!
Exactly I was using the search and filter I have modified the condition below where I wanted to select workspaces that contain the keyword for example wall.
```
filter_setup = {
    "and": [
        {
        "attributeName": "workspace",
        "operator": "eq",
        "attributeValue": "myworkspace"
        },
        filter_setup = {
    "and": [
        {
       attributeValue": "wall"
       "operator": "contains",
       "attributeName": "workspace",
      
        }
    ]
}
search = client.discovery.search_entities("*", search_filter=filter_setup)
```
Solved my issue!
Thanks!
