### ISSUE TITLE
Input and Output information not parsing through excel file for custom lineage.

### ISSUE THREAD

**Issue by huzaifahpathan** [wjohnson/pyapacheatlas#256]
No worries I solved it.

**Comment by huzaifahpathan** [comment]
It is not parsing the description for entity defs also from the excel sheet :S

**Comment by wjohnson** [comment]
@huzaifahpathan Are you still having troubles?  Any examples you could share?

**Comment by wjohnson** [comment]
Closing as it looks like it was solved!  Please let me know if you have any other concerns or need for help!
