### ISSUE TITLE
Skip empty sheets/files when parsin

### ISSUE THREAD

**Issue by mwbrent** [wjohnson/pyapacheatlas#260]
Instead generating an error, it would be preferable for the parser to disregard empty files while parsing an Excel file, allowing it to proceed to the next block seamlessly. This approach ensures a smoother execution and enhanced user experience.

**Comment by wjohnson** [comment]
Hi, @mwbrent thank you so much for using PyApacheAtlas!

Would you be able to share an example of an empty file and the error you're receiving?

I don't want to make any assumptions about a user's file.  It sounds like you might have a set of excel files you're trying to parse?  If that's the case, you might use a try/catch block inside of your loop to catch the error and silently ignore it if you can be confident the empty file is okay to be there.

**Comment by wjohnson** [comment]
Closing as it's been a while but please feel free to re-open if you can share a sample of what you're experiencing or would like to see.
