### ISSUE TITLE
Automate the creation of relationships between Power BI, Azure Synapse, Oracle,and Azure storage account (Purview Apache Atlas)?

### ISSUE THREAD

**Issue by JavaPr288** [wjohnson/pyapacheatlas#261]
Really Cool API and loved the videos on Youtube!
**What is your desired outcome**
Using the API to "automatically" create or update the relationships between your Power BI, Azure Synapse, Oracle , Google, and Azure storage account entities in your Purview collections using the Azure Purview REST API. I work in marketing and we have lots of different data sources and datasets .
With the API I can manually upload an Excel File to map different datasets but is there a more automated way to do that?

**Goal:** Use a Python script that can either use regular expressions or other features of the API to find the Synapse, Oracle datasets that correspond to the Power BI reports by their name or attributes and then link them without manual intervention.

**What have you tried so far**
Used the API and Excel spreadsheets to update the metadata and it works.

**Additional context**
Really open to any suggestions to save time from the manual workflow.

**Comment by wjohnson** [comment]
Hi, @JavaPr288 - Thank you for using PyApacheAtlas!

I think the answer is **yes** although it will require much more development effort and PyApacheAtlas doesn't help with nearly any of it.

I think this breaks down to a few steps:

1. You need to understand what are the relationships - When you do this manually, you might be looking at the UI and can quickly jot it down but now using code, you'll need to find the Power BI APIs that return the data set dependencies.
2. You need to work out the fully qualified names - You can get this from the `get_typedefs` method but you'd have to be able to retrieve all the necessary parts from the Power BI dependency API calls. This might get tricky if it doesn't return, for example, the synapse db schema.
3. You need to actually create lineage - I have [samples](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/create_entity_and_lineage.py#L55-L62) for that!
4. You need to automate - This is perhaps the trickiest. Do you want to automate as in you have a script with a dataset id in power bi and it goes and updates all of the lineage for you? Do you want to [listen](https://learn.microsoft.com/en-us/purview/configure-event-hubs-for-kafka) for whenever a PBI dataset asset is created in Purview and then react to it? Both are possible but the listener might be much more difficult to accomplish.

Can you share more about your desired workflow and maybe we can brainstorm some ideas on this thread or others might pipe in to share their automation approaches?

**Comment by JavaPr288** [comment]
Hi,
Thanks for your reply really appreciate it!
Great I've got the first 3 points done; watched your videos and tried out the code samples for custom lineage.
For point 4 I'll take whatever I can get lol using Purview and pyapacheatlas .
We have a Purview weekly scan and I'm planning to run a Python job afterwards that would update relationships based on the data in Azure Purview (Power BI and other).
I'd also plan to run this script once in the beginning to get the relationships. I'm shooting for a target accuracy of 80% after that can live some manual adjustment.
thanks
