### ISSUE TITLE
Enhance bulk template to allow upload terms not just in default Glossary

### ISSUE THREAD

**Issue by KellyG123** [wjohnson/pyapacheatlas#264]
**Describe the feature**
Current Excel bulk template & **client.upload_entities** is hard coded to upload entities with terms that are created in default Glossary. I want to use it upload terms that are created in custom Glossary as well.

**Detailed Example**
If I upload a term call Markdown created in "Finance Glossary" (qualified name is Markdown@Finance Glossary, it will fail.

**Suggested Implementation**
Allow to upload terms that are created in custom Glossary.

**Comment by wjohnson** [comment]
@KellyG123  this was a great suggestion!  I've now implemented this in 0.16.0. You can now set the `default_glossary` in the `ExcelConfiguration` object AND in the Excel cell, you can manually override this with `myTerm@My Other Glossary` if you want to mix and match across different glossaries.  Thank you for the great suggestion and continued use of PyApacheAtlas!
