### ISSUE TITLE
Add Support for Purview GraphQL API Queries (Currently in Purview Preview Status)

### ISSUE THREAD

**Issue by nigelmeakins** [wjohnson/pyapacheatlas#265]
**Describe the feature**
The GraphQL API (in Preview) allows for querying of entities and related entities, as shown in the following tutorial:
https://learn.microsoft.com/en-us/purview/tutorial-graphql-api

Having a GraphQL client and related methods for executing the API calls in https://{{endpoint}}/datamap/api/graphql

would allow for much richer retrieval of entity sets based on related entities and their attributes.

**Detailed Example**
Please see the tutorial at https://learn.microsoft.com/en-us/purview/tutorial-graphql-api
for examples of functionality provided by GraphQL.

**Issues that this feature solves**
None known

**Suggested Implementation**
Similarly to the pyapacheatlas.core.discovery.purview.PurviewDiscoveryClient, a ...purview.GraphQLClient could then implement the required query method for executing GraphQL queries against Purview

**Additional context**
See https://graphql.org/learn/ for basics of GraphQL.

**Comment by wjohnson** [comment]
@nigelmeakins thank you for this awesome suggestion!  I've implemented a bare bones support for it but would love your feedback on how to make it more useful for the budding user of GraphQL.  Please see `PurviewClient.graphql.query` to execute a search query.

**Comment by nigelmeakins** [comment]
Great, thanks very much. I'll get back to you on suggested extensions once I've taken it for a spin.
