### ISSUE TITLE
Trying to update purview contacts (expert and owner) but not able to do it

### ISSUE THREAD

**Issue by vjcuadros** [wjohnson/pyapacheatlas#266]
**Describe the bug**
Behavior is weird as it appears as it succeed, but when I go to purview entity contacts are not there, but when I go to filters I can filtered by those contacts. not sur if purview bug or sdk.

**To Reproduce**
I'm using this code

actual_entity = AtlasEntity(
        name=name,
        qualified_name=qualified_name,
        typeName=typeName,
         attributes={
            "userDescription": description
        },
        guid=guid,
   contacts ={"Expert":[{"id":"aad-id-of-some-user", "info":""}], "Owner":[]}
)

**Comment by vjcuadros** [comment]
do you know if there is a near release date?

**Comment by Sgidwani61** [comment]
nope ive been waiting for one since august

**Comment by wjohnson** [comment]
@Sgidwani61 @vjcuadros Thank you both for your _extreme_ patience.  I just published a new release and it is now available on PyPi with the fix.  With time off for the holidays I was finally able to get this out.  Thank you both for your continued use of PyApacheAtlas!
