### ISSUE TITLE
Can't upload child terms

### ISSUE THREAD

**Issue by SIlviaBruggi** [wjohnson/pyapacheatlas#276]
Hello, in purview I have the following hierarchy of terms: 
![image](https://github.com/wjohnson/pyapacheatlas/assets/67733876/ef00d79b-ce80-4b7c-9553-0895ed63d675)
In  the excel template in the BulkEntities sheet I have added the column "[Relationship] meanings" and I want to use it to connect the "agreement" term with one of the existing tables. If I try to connect the upper level term ( writing customer@General in the [Relationship] meanings column) it works, but if I try with agreement@General it gives me this error:

"errorMessage":"Referenced entity AtlasObjectId{guid='null', typeName='AtlasGlossaryTerm', uniqueAttributes={qualifiedName:agreement@General}} is not found"}

Same happens with the other levels: contract and contract connection

What am I doing wrong? How do you have to write in the excel template terms that are not in the first layer of the glossary but are some levels below? The "agreement" term is part of the General glossary though...
Thanks
Silvia

**Comment by wjohnson** [comment]
Hi, @SIlviaBruggi thank you for your use of PyApacheAtlas!

Please see this section of the doc that lightly documents the fully qualified name behavior of child terms.
https://wjohnson.github.io/pyapacheatlas-docs/latest/readers/excel-config.html?highlight=parent%20term#column-headers-with-special-meanings

It could be as simple as `contract connection_agreement@General` but might be as complicated as concatenating all of those glossary terms together.

You should also be able to see the fully qualified name on the glossary term page itself I believe or if you use [get_term](https://wjohnson.github.io/pyapacheatlas-docs/latest/core/glossary/api/pyapacheatlas.core.glossary.glossaryclient.GlossaryClient.get_term.html?highlight=get_term) you should be able to retrieve the details when you use the guid.

**Comment by SIlviaBruggi** [comment]
It worked indicating the term like this: customer_contract_contract connection_agreement@General 
Thanks for your tip, great package by the way!
Silvia

**Comment by SIlviaBruggi** [comment]
.

**Comment by wjohnson** [comment]
Glad you got it to work by concatenating all of those terms together!
