### ISSUE TITLE
Sent relationships are not visible with excel_bulk_entities_upload.py

### ISSUE THREAD

**Issue by fBedecarrats** [wjohnson/pyapacheatlas#67]
Congratulations and many thanks for this great tool!
The sample provided are very useful but I cannot figure out how the custom attributes and relationships are passed to the Atlas API.
For instance, the script [samples/excel/excel_bulk_entities_upload.py](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/excel/excel_bulk_entities_upload.py) produces an excel BulkEntities sheet with two additional columns: "[Relationship] table", and "type".
The corresponding information is visible in the dict outputed by excel_reader.parse_bulk_entities(), but I cannot find them in the result of client.upload_entities() that also get printed on the console (see below). How are the attributes "[Relationship] table", and "type" passed to Apache Atlas in this case?
I would really need to understand that to grasp exactly what kind of related objects I can pass to the catalog API with pyapacheatlas.

```
runfile('C:/Users/FBEDECARRA/Desktop/Tests Apache Atlas/sample_bulk_upload.py', wdir='C:/Users/FBEDECARRA/Desktop/Tests Apache Atlas')
{
  "mutatedEntities": {
    "CREATE": [
      {
        "typeName": "DataSet",
        "attributes": {
          "qualifiedName": "pyapacheatlas://dataset",
          "name": "exampledataset"
        },
        "guid": "f24c4f22-c5e3-4776-a630-41e533b47099",
        "status": "ACTIVE",
        "displayText": "exampledataset",
        "classificationNames": [],
        "classifications": [],
        "meaningNames": [],
        "meanings": [],
        "isIncomplete": false,
        "labels": []
      },
      {
        "typeName": "hive_table",
        "attributes": {
          "createTime": 0,
          "qualifiedName": "pyapacheatlas://hivetable01",
          "name": "hivetable01"
        },
        "guid": "46efb945-281d-497b-8334-92c668fb8d5b",
        "status": "ACTIVE",
        "displayText": "hivetable01",
        "classificationNames": [],
        "classifications": [],
        "meaningNames": [],
        "meanings": [],
        "isIncomplete": false,
        "labels": []
      },
      {
        "typeName": "hive_column",
        "attributes": {
          "qualifiedName": "pyapacheatlas://hivetable01#colA",
          "name": "columnA"
        },
        "guid": "195d4775-69f0-48fe-b63c-88c0e30066fa",
        "status": "ACTIVE",
        "displayText": "columnA",
        "classificationNames": [],
        "classifications": [],
        "meaningNames": [],
        "meanings": [],
        "isIncomplete": false,
        "labels": []
      },
      {
        "typeName": "hive_column",
        "attributes": {
          "qualifiedName": "pyapacheatlas://hivetable01#colB",
          "name": "columnB"
        },
        "guid": "f43b8f63-63da-4c82-b5f5-2b09c0418e67",
        "status": "ACTIVE",
        "displayText": "columnB",
        "classificationNames": [],
        "classifications": [],
        "meaningNames": [],
        "meanings": [],
        "isIncomplete": false,
        "labels": []
      },
      {
        "typeName": "hive_column",
        "attributes": {
          "qualifiedName": "pyapacheatlas://hivetable01#colC",
          "name": "columnC"
        },
        "guid": "f1650ead-6b7e-4dce-aa2b-03ddb18ebca3",
        "status": "ACTIVE",
        "displayText": "columnC",
        "classificationNames": [],
        "classifications": [],
        "meaningNames": [],
        "meanings": [],
        "isIncomplete": false,
        "labels": []
      }
    ]
  },
  "guidAssignments": {
    "-1005": "f1650ead-6b7e-4dce-aa2b-03ddb18ebca3",
    "-1004": "f43b8f63-63da-4c82-b5f5-2b09c0418e67",
    "-1001": "f24c4f22-c5e3-4776-a630-41e533b47099",
    "-1003": "195d4775-69f0-48fe-b63c-88c0e30066fa",
    "-1002": "46efb945-281d-497b-8334-92c668fb8d5b"
  }
}
Completed bulk upload successfully!
Search for hivetable01 to see your results.
```

**Comment by wjohnson** [comment]
@fBedecarrats I apologize for not getting back to you sooner!  Apparently I need to turn on notifications of new issues!

Your specific ask is a bit buried in the readers module.  Specifically, [these lines](https://github.com/wjohnson/pyapacheatlas/blob/94d9d9bc794326564734f81aeb28faceff50cd2b/pyapacheatlas/readers/reader.py#L111-L124) (111-124 of reader.py) show the following steps:

* While parsing the rows, it looks to see if the header begins with `[Relationship]`
* If so, it removes the token `[Relationship]` and assumes anything afterwards is the relationship attribute name.
* The Relationship column should reference an entity that was already "created" in a preceding line.
* The algorithm then looks up this referenced entity.
* The referenced entity's main attributes (temporary guid, typeName, and qualifiedName) are then appended to the current row's "relationshipAttributes" field.

You don't see it on that particular output as that is the response from Purview.  If you call `client.get_entity("46efb945-281d-497b-8334-92c668fb8d5b")` you should see the relationshipAttributes field with an array of hive_column entities.

If you really want to learn how the relationships work, you can take a look at this [CRUD sample](https://github.com/wjohnson/pyapacheatlas/blob/master/samples/CRUD/create_relationships.py) instead that shows creating a table from scratch and different ways of instantiating the relationship between table and columns (either through the array on the table or the single table reference from each column).

**Comment by fBedecarrats** [comment]
Thank you for your answer, it is very useful. I must say it is a smart trick! I think it would be useful to give some hints on how a user could handle this feature (besides the demo template) in pyapacheatlas/samples/excel/README.md. 
I'm closing the issue/question. Thanks again.
PS : I have been testing several import scenarios with pyapacheatlas and I have some suggestions about useful complementary functionalities (creating classifications from Excel, defining entity of a different SuperType than DataSet...). I'll mention them as new issues. Please feel free to ignore and close them if it doesn't fit your roadmap.

**Comment by wjohnson** [comment]
@fBedecarrats  - I love the feedback!  Thank you so much for investing your time in exploring the package and offering suggestions!  I will also provide some better details on the excel README for how users can take advantage of the relationship attributes.
