### ISSUE TITLE
The `is_purview` attribute is not set correctly.

### ISSUE THREAD

**Issue by th0ger** [wjohnson/pyapacheatlas#76]
When the client is created with `PurviewClient()`, the `is_purview` client attribute is incorrectly set to `False`.
This causes `search_entities()` to throw `RuntimeWarning: You're using a Purview only feature on a non-purview endpoint`:

```
from pyapacheatlas.auth import ServicePrincipalAuthentication
from pyapacheatlas.core import PurviewClient

auth = ServicePrincipalAuthentication(
    tenant_id = "...", 
    client_id = "...", 
    client_secret = "..."
)

client = PurviewClient(
    account_name = "my-purview-account-name",
    authentication = auth
)

print('client.is_purview:', client.is_purview)
# >> False

for i in client.search_entities('totemove'):
    print(i)
# >> ...python3.9/site-packages/pyapacheatlas/core/util.py:18: 
# >> RuntimeWarning: You're using a Purview only feature on a non-purview endpoint.
# >> warnings.warn(
```

The output is ok, despite this warning.

Workaround: Set `client.is_purview = True` after client creation.

**Comment by wjohnson** [comment]
Ah!  Thanks for discovering that @th0ger !!  I'll get that cleaned up by the release for this weekend!

**Comment by wjohnson** [comment]
So, turns out I am not the [hero with a new skill](https://xkcd.com/208/) as the regex I was using didn't account for hyphens in the service name.  🤦  Thanks for calling out the issue and trying more unique Purview names than what I did!

**Comment by th0ger** [comment]
Keep up the good work!

**Comment by wjohnson** [comment]
The changes are now made in the pypi version 0.4.0 after 7b32151e546b18979eaf2a8f08d3aa89189e2049 was released.

Thank you for your patience!
