### ISSUE TITLE
get_entity error when trying to retrieve database object

### ISSUE THREAD

**Issue by zsponaugle** [wjohnson/pyapacheatlas#88]
Hello,

I am trying to retrieve data about the synapse (azure_sql_dw) instance I have setup in our Purview catalog. However when I try to get that information via get_entity, it returns an error.

Here is the code --

azure_sql_dw = client.get_entity(guid='c39966cb-fbe1-4394-9b44-1d3bbafeb38e')

Here is the error  --

HTTPError: 500 Server Error: Internal Server Error for url: https://XXXXXXXXXXXX.catalog.purview.azure.com/api/atlas/v2/entity/bulk?guid=c39966cb-fbe1-4394-9b44-1d3bbafeb38e

Any idea on what could be causing this? Calls I make to table or column objects work fine.

Thanks,
Zack

**Comment by wjohnson** [comment]
@zsponaugle Yikes!  I'm assuming you can find the azure sql dw in the Purview UI, right?  You may want to work backwards from the table.

Query the table and look in its relationship attributes for `dbSchema`.  Get the guid from there and that will return a `azure_sql_dw_schema` type.  In the `azure_sql_dw_schema` can you confirm that you see the same guid in the `dataWarehouse` relationship attribute that you're trying to query?

I'm curious if the Purview UI is showing something other than the real entity that can be queried.

**Comment by zsponaugle** [comment]
Hi Will,

Yes I can view the azure sql in the Purview UI. I also compared the GUID's and they do match.

A couple other comments --

-I am able to use get_entity on SQL Server databases just fine. Only Synapse appears to be an issue.

-I also tried looking it up using qualifiedName and typeName:

client.get_entity(qualifiedName='mssql://XXXXX.database.windows.net/XXXXXXXX'
                            ,typeName="azure_sql_dw"
                            )

but this returns the same error.

Thank you for the help.
Zack

**Comment by bsherwin** [comment]
@zsponaugle - when you use Purview Studio to browse to the Synapse DW, your URL should look like:

`.../main/catalog/browseassettypes/assettype/detail?browseEntityType=azure_sql_dw&browseGuid=c4451d60-5a65-4f3d-9b3c-3b532de2258c&feature.tenant=...`

The GUID for your code would be the "browseGuid" value. Is that what you are seeing?

**Comment by zsponaugle** [comment]
@bsherwin Hi, I understand now. I can also confirm that GUID from the URL also matches the one I am getting in the API.

**Comment by wjohnson** [comment]
@zsponaugle Sorry for the delay on this.  Would you mind re-scanning your Synapse DW and trying again?  I was able to set up a scan on a Synapse DB and then I was able to navigate from the table all the way up to the server.  Starting from the table, I grabbed the guid from the relationship attributes.

* dbSchema relationship attribute (on the table)
* dataWarehouse relationship attribute (on the azure_sql_dw_schema object)
* server relationship attribute (on the azure_sql_dw object)

If you still have an issue, I'd suggest opening a support ticket with Microsoft.

**Comment by wjohnson** [comment]
Closing it out but happy to have this re-opened if anything else points to the package as being the issue :(
