### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by shershahkhan** [wjohnson/pyapacheatlas#89]
HI,
I am trying to run the code and create a sample entity but i am getting the following error. I have checked the credentials and everything seems fine. 

Traceback (most recent call last):
  File "c:\Users\shkh\Purview.py", line 105, in <module>
    batch=[output01, input01, process]
  File "C:\Users\shkh\AppData\Roaming\Python\Python36\site-packages\pyapacheatlas\core\client.py", line 927, in upload_entities
    headers=self.authentication.get_authentication_headers()
  File "C:\Users\shkh\AppData\Roaming\Python\Python36\site-packages\pyapacheatlas\auth\serviceprincipal.py", line 58, in get_authentication_headers
    self._set_access_token()
  File "C:\Users\shkh\AppData\Roaming\Python\Python36\site-packages\pyapacheatlas\auth\serviceprincipal.py", line 48, in _set_access_token
    self.expiration = datetime.fromtimestamp(int(authJson["expires_in"]))
OSError: [Errno 22] Invalid argument

**Comment by bsherwin** [comment]
Can you verify your credentials and connectivity by doing a simple read? This would seem that you did not get a valid access_token back from the oauth request.

```
import os
import json

from pyapacheatlas.auth import ServicePrincipalAuthentication
from pyapacheatlas.core import PurviewClient, AtlasEntity, AtlasProcess

oauth = ServicePrincipalAuthentication(
    tenant_id = os.environ.get('AZURE_TENANT_ID', ''),
    client_id = os.environ.get('AZURE_CLIENT_ID', ''),
    client_secret = os.environ.get('AZURE_CLIENT_SECRET', '')
    )
client = PurviewClient(
    account_name = os.environ.get('PURVIEW_CATALOG_NAME', ''),
    authentication = oauth
    )
all_type_defs = client.get_all_typedefs()
print(all_type_defs)
```

**Comment by shershahkhan** [comment]
HI
Still the same error when I am running using a Python Script. If i use
Jupyter and do Az Login then the code is working fine. Seems like the Auth
token is having some issues when running .py script.

[image: image.png]


Best Regards
Sher Shah Khan

**Comment by bsherwin** [comment]
@shershahkhan I was able to replicate this issue on a Windows 10 Powershell window running Python 3.6. I find it interesting that this code runs fine in bash. I think the fix is in the PR listed above, but @wjohnson will have to confirm.

**Comment by wjohnson** [comment]
@shershahkhan The latest version in Github fixes the issue for PowerShell.  Thank you @bsherwin for investigating and finding a fix for this!

**Comment by wjohnson** [comment]
@shershahkhan latest release on PyPi now reflects Brian's changes!
https://pypi.org/project/pyapacheatlas/0.4.1/
