### ISSUE TITLE
Bulk column UPDATE

### ISSUE THREAD

**Issue by zsponaugle** [wjohnson/pyapacheatlas#95]
Hello,

Would your samples/excel/excel_bulk_entities_upload.py work for **updating** existing columns? I am trying to find a way to bulk update columns that have already been scanned in via the GUI. We want to add additional information to the columns, mainly descriptions and glossary links.

I am trying to test it by updating a single column (adding a description to it). Below is what I have in the spreadsheet.

typeName | name | qualifiedName | classifications | [Relationship] table | type | description
-- | -- | -- | -- | -- | -- | --
mssql_column | my_column | mssql://XXXXXXXXXXX:XXXXXXX/MSSQLSERVER/XXXXX/XXXXX/my_table#my_column |   | pyapacheatlas://my_table | smallint | testing

Running this gives me the following error --

**KeyError: 'The entity pyapacheatlas://my_table should be listed before mssql://XXXXXXXXXXX:XXXXXXX/MSSQLSERVER/XXXXX/XXXXX/my_table#my_column.'**

I am not sure how to interpret this. Any help is greatly appreciated. Thank you.

**Comment by zsponaugle** [comment]
Oops...I understand it now. =]

Like this --

typeName | name | qualifiedName | classifications | [Relationship] table | type | description
-- | -- | -- | -- | -- | -- | --
mssql_table | my_table| mssql://XXXXXXXXXXX:XXXXXXX/MSSQLSERVER/XXXXX/XXXXX/my_table |   |   |   |  
mssql_column | my_column | mssql://XXXXXXXXXXX:XXXXXXX/MSSQLSERVER/XXXXX/XXXXX/my_table#my_column |   | mssql://XXXXXXXXXXX:XXXXXXX/MSSQLSERVER/XXXXX/XXXXX/my_table | smallint | testing

**Comment by wjohnson** [comment]
@zsponaugle thank you for using the package!  And yes, the bulk entities excel parser will definitely work for UPDATING.

Glossary links are currently not supported but on the to do list with issue #74 . I plan to do some work this weekend and hopefully will find a way to support it in the excel way.

As for updating descriptions, your excel worksheet would only need to specify that field and any required fields.  And as you saw, even the relationship attributes need to be specified.

I'm glad you got it working!!
