### ISSUE TITLE
excel_custom_table_column_lineage question

### ISSUE THREAD

**Issue by zsponaugle** [wjohnson/pyapacheatlas#97]
Hi,

I am trying to figure out how to add column specific lineage. I have ran the **excel_custom_table_column_lineage** sample but am not seeing any lineage in the interface. The demo tables and columns are uploaded but I do not see a lineage tab. Are there any changes I need to make to the sample code beside entering the authentication information?

The **excel_update_lineage_upload** sample works fine for me but this only shows table lineage.

Thank you,
Zack

**Comment by wjohnson** [comment]
Hi, @zsponaugle ! Thank you for your continued use of the PyApacheAtlas pakage!

Would you mind sharing the results of a get_entity(guid="...") on that process entity that was created?

I'll try to reproduce on my end.  Thank you for your patience!

**Comment by wjohnson** [comment]
In addition, @zsponaugle I also ran `client.get_entity_lineage("...")` and I was able to get a complete response on the DestTable01.

**Comment by zsponaugle** [comment]
Hi Will. Sure thing. Below are the get_entity results for the **daily_etl** process created by the default template. Let me know if you also want the output for the other two processes created (weekly_etl, stored_proc:do_something).

`{'referredEntities': {}, 'entities': [{'typeName': 'demo_process', 'attributes': {'owner': None, 'outputs': [{'guid': '6f0fa6ed-6479-4ea5-ac95-cca0632eadb9', 'typeName': 'demo_table', 'uniqueAttributes': {'qualifiedName': 'DestTable01'}}], 'replicatedTo': None, 'replicatedFrom': None, 'qualifiedName': 'Daily_ETL', 'inputs': [{'guid': '55a328c9-5397-4bff-b5f9-5ad2797a99af', 'typeName': 'demo_table', 'uniqueAttributes': {'qualifiedName': 'SourceTable01'}}, {'guid': 'a5cfc30e-bdf5-4fd8-b038-ebf354e1724a', 'typeName': 'demo_table', 'uniqueAttributes': {'qualifiedName': 'SourceTable02'}}], 'name': 'Daily_ETL', 'errorMessage': None, 'description': None, 'status': None, 'columnMapping': '[{"ColumnMapping": [{"Source": "source_c01", "Sink": "dest_c01"}, {"Source": "source_c02", "Sink": "dest_c02"}, {"Source": "source_c03", "Sink": "dest_combo01"}], "DatasetMapping": {"Source": "SourceTable01", "Sink": "DestTable01"}}, {"ColumnMapping": [{"Source": "source_c04", "Sink": "dest_combo01"}], "DatasetMapping": {"Source": "SourceTable02", "Sink": "DestTable01"}}]'}, 'lastModifiedTS': '1', 'guid': '0b7bb266-8a8a-4b8b-80ef-289ad1cf4871', 'status': 'ACTIVE', 'createdBy': '7e9d07a7-00b5-4241-b068-3fd878d7f809', 'updatedBy': '7e9d07a7-00b5-4241-b068-3fd878d7f809', 'createTime': 1614110514429, 'updateTime': 1614110514429, 'version': 0, 'relationshipAttributes': {'outputs': [{'guid': '6f0fa6ed-6479-4ea5-ac95-cca0632eadb9', 'typeName': 'demo_table', 'entityStatus': 'ACTIVE', 'displayText': 'DestTable01', 'relationshipType': 'process_dataset_outputs', 'relationshipGuid': '3c9429f4-b0d5-4571-b01e-70da0665f977', 'relationshipStatus': 'ACTIVE', 'relationshipAttributes': {'typeName': 'process_dataset_outputs'}}], 'inputs': [{'guid': '55a328c9-5397-4bff-b5f9-5ad2797a99af', 'typeName': 'demo_table', 'entityStatus': 'ACTIVE', 'displayText': 'SourceTable01', 'relationshipType': 'dataset_process_inputs', 'relationshipGuid': '2b86a86c-e8d2-4d64-a9be-66617d737459', 'relationshipStatus': 'ACTIVE', 'relationshipAttributes': {'typeName': 'dataset_process_inputs'}}, {'guid': 'a5cfc30e-bdf5-4fd8-b038-ebf354e1724a', 'typeName': 'demo_table', 'entityStatus': 'ACTIVE', 'displayText': 'SourceTable02', 'relationshipType': 'dataset_process_inputs', 'relationshipGuid': '8f438be0-3c2c-48fe-af72-c8618108e4c5', 'relationshipStatus': 'ACTIVE', 'relationshipAttributes': {'typeName': 'dataset_process_inputs'}}], 'columnLineages': [], 'meanings': []}}]}`

I also ran get_entity_lineage on SourceTable01 and that appears to return the proper information as well. Here is the output:

`{'baseEntityGuid': '55a328c9-5397-4bff-b5f9-5ad2797a99af', 'lineageDirection': 'BOTH', 'lineageDepth': 3, 'lineageWidth': 10, 'childrenCount': -1, 'guidEntityMap': {'6f0fa6ed-6479-4ea5-ac95-cca0632eadb9': {'typeName': 'demo_table', 'attributes': {'qualifiedName': 'DestTable01', 'name': 'DestTable01'}, 'lastModifiedTS': '1', 'guid': '6f0fa6ed-6479-4ea5-ac95-cca0632eadb9', 'status': 'ACTIVE', 'displayText': 'DestTable01', 'classificationNames': [], 'meaningNames': [], 'meanings': []}, '0b7bb266-8a8a-4b8b-80ef-289ad1cf4871': {'typeName': 'demo_process', 'attributes': {'qualifiedName': 'Daily_ETL', 'name': 'Daily_ETL', 'columnMapping': '[{"ColumnMapping": [{"Source": "source_c01", "Sink": "dest_c01"}, {"Source": "source_c02", "Sink": "dest_c02"}, {"Source": "source_c03", "Sink": "dest_combo01"}], "DatasetMapping": {"Source": "SourceTable01", "Sink": "DestTable01"}}, {"ColumnMapping": [{"Source": "source_c04", "Sink": "dest_combo01"}], "DatasetMapping": {"Source": "SourceTable02", "Sink": "DestTable01"}}]'}, 'lastModifiedTS': '1', 'guid': '0b7bb266-8a8a-4b8b-80ef-289ad1cf4871', 'status': 'ACTIVE', 'displayText': 'Daily_ETL', 'classificationNames': [], 'meaningNames': [], 'meanings': []}, '55a328c9-5397-4bff-b5f9-5ad2797a99af': {'typeName': 'demo_table', 'attributes': {'qualifiedName': 'SourceTable01', 'name': 'SourceTable01'}, 'lastModifiedTS': '1', 'guid': '55a328c9-5397-4bff-b5f9-5ad2797a99af', 'status': 'ACTIVE', 'displayText': 'SourceTable01', 'classificationNames': [], 'meaningNames': [], 'meanings': []}}, 'includeParent': False, 'relations': [{'fromEntityId': '55a328c9-5397-4bff-b5f9-5ad2797a99af', 'toEntityId': '0b7bb266-8a8a-4b8b-80ef-289ad1cf4871', 'relationshipId': '2b86a86c-e8d2-4d64-a9be-66617d737459'}, {'fromEntityId': '0b7bb266-8a8a-4b8b-80ef-289ad1cf4871', 'toEntityId': '6f0fa6ed-6479-4ea5-ac95-cca0632eadb9', 'relationshipId': '3c9429f4-b0d5-4571-b01e-70da0665f977'}], 'parentRelations': [], 'widthCounts': {'OUTPUT': {}, 'INPUT': {}}}`

So everything seems to be connected properly under the hood but the UI isn't showing the lineage tab for the tables.

**Comment by zsponaugle** [comment]
I looked again today and the lineage tabs are now showing. I wonder if there was some lag in the system? Closing ticket. Thanks.
