### ISSUE TITLE
Documentation seems incorrect about "Search (only for Azure Purview advanced search)"

### ISSUE THREAD

**Issue by mauriciojost** [wjohnson/pyapacheatlas#98]
As far as I understand PurView offers a very limited API for searches when compared to [the original Apache Atlas](https://atlas.apache.org/api/v2/index.html). One example: there is no `v2/search/basic` in PurView, but there is in Atlas . 

In the light of this information, did you mean this instead in the README.md?
```
Search (the only search available for Azure Purview advanced search)
```

And as a side question, do you know if the original Atlas API is still accessible somehow?

**Comment by wjohnson** [comment]
Hi @mauriciojost ! Thank you using the PyApacheAtlas package!

If you are using Purview, you are stuck with just the advanced search built into the service. The engineers have not implemented the other search mechanisms like dsl or basic. As a result, if you were to call those endpoints you'd get an error response from Purview.

The package in this repo only supports that advanced search feature (as the primary purpose of this repo is to support Purview).

Does that help clarify things?

**Comment by wjohnson** [comment]
Closing as it looks like things were clarified.

**Comment by mauriciojost** [comment]
Thanks for your clarifications!
